### PR TITLE
Added category for API methods

### PR DESCRIPTION
**Pull request by subhamskm**
Bugzilla Bug: [1551848](https://bugzilla.mozilla.org/show_bug.cgi?id=1551848)

### CODE REVIEW

**Comment by subhamskm** [comment]
Where can I find the declarations?

**Comment by djmitche** [comment]
They are mostly in `services/*/src/api.js`.  But you'll need to keep looking until all of the tests pass.

**Comment by subhamskm** [comment]
I think I have added category to every declaration. Still some tests are not passing.

**Comment by djmitche** [comment]
It looks like there are a few more instances to find!

```
AssertionError [ERR_ASSERTION]: Option 'category' must be provided
    at /taskcluster/libraries/api/src/index.js:112:7
    at Array.forEach (<anonymous>)
    at APIBuilder.declare (/taskcluster/libraries/api/src/index.js:111:69)
    at Suite.<anonymous> (/taskcluster/libraries/api/test/logging_test.js:26:11)
```
that last line points at the error.  You would get the same result running the tests locally, I expect.  Similarly for

```
AssertionError [ERR_ASSERTION]: Option 'category' must be provided
    at /taskcluster/libraries/api/src/index.js:112:7
    at Array.forEach (<anonymous>)
    at APIBuilder.declare (/taskcluster/libraries/api/src/index.js:111:69)
    at Object.<anonymous> (/taskcluster/services/auth/test/helper.js:218:20)
```

Also, https://tools.taskcluster.net/groups/dLo7xzEaRF-gptiau6FiaQ/tasks/Kz7kRUFRTG600zrR4BA65w/runs/0/logs/public%2Flogs%2Flive.log shows some places where you've spelled it "TaskCluster".  The "c" in the middle should be lower-case.

Almost there!  This is the kind of big, repetitive patch that I usually do while watching some TV show to keep me from getting too bored..

**Comment by subhamskm** [comment]
Finally!

**Comment by djmitche** [comment]
All green!  I'll have a look.  While I do, think about how you'll implement the next step?

**Pull request merged**
