### PR TITLE
Switch to Node 10.15.1

### PR DESCRIPTION
**Pull request by owlishDeveloper**
Bugzilla Bug: [1526607](https://bugzilla.mozilla.org/show_bug.cgi?id=1526607)

### CODE REVIEW

**Comment by owlishDeveloper** [comment]
Yeah, I'll upload the image in a moment. Images take a while for me because of my crappy internets at home :)

**Comment by owlishDeveloper** [comment]
(@djmitche you were looking at flakes? In this taskgroup there might be a flake - the queue test passed after I retriggered)

**Comment by djmitche** [comment]
I was / am.  File a bug linking to the failed run with the mocha summary of the exception?

**Comment by owlishDeveloper** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1526712 created

**Comment by djmitche** [comment]
:cake:

**Pull request merged**
