### PR TITLE
Revert "[UI] Migrate to material-ui v4"

### PR DESCRIPTION
**Pull request by helfi92**
Reverts taskcluster/taskcluster#1729

1. Something is off in the task group view

Screen Shot 2019-11-14 at 11 36 08 AM

2. Clicking on an action from the speed dial then pressing escape throws an error:

Screen Shot 2019-11-14 at 11 36 35 AM

### CODE REVIEW

**Comment by Rolikasi** [comment]
How can i reproduce it?

**Comment by helfi92** [comment]
You can reproduce by viewing any task group (first error) and task (second error).

**Comment by Rolikasi** [comment]
- [x] fix tables in task group view
- [ ] fix error

**Comment by Rolikasi** [comment]
When I click on an action from the speed dial then pressing escape throws an error:
action is null

**Comment by helfi92** [comment]
> action is null

Yeah, I saw this error as well.

**Comment by Rolikasi** [comment]
Hmm, can't understand what is `action={actions => actions.focusVisible()}` in DialogAction for?
<Button
            disabled={executing}
            onClick={onClose}
            action={actions => actions.focusVisible()}>

I deleted `action` and error disappear

**Comment by helfi92** [comment]
This was a hack that would put the focus on the "Cancel" button when the user opens the dialog.

**Comment by helfi92** [comment]
_Example: focus is on "Cancel"_
Screen Shot 2019-11-14 at 1 08 47 PM

**Comment by helfi92** [comment]
https://github.com/mui-org/material-ui/issues/13387

**Comment by helfi92** [comment]
You can try just using the `autoFocus` prop on the button instead of  `action={actions => actions.focusVisible()}` and check if that works.

**Comment by Rolikasi** [comment]
I've already tried, not working(

**Comment by helfi92** [comment]
I'm using autofocus in the dialog in a different repo and it works https://github.com/mozilla-frontend-infra/balrog-ui/blob/b65cfaa765aaf0179e93ead7f2a709550a54dd85/src/components/DialogAction/index.jsx#L110. I just tested this on Firefox.

**Comment by Rolikasi** [comment]
I checked autofocus in different browsers and with material-ui v3, it's not working. May be because Button components are different in these repos

**Comment by helfi92** [comment]
Ok, feel free to just remove `action={actions => actions.focusVisible()}` then we could file a separate issue to add it back.

**Comment by Rolikasi** [comment]
Should I make a new PR?

**Comment by helfi92** [comment]
Sure.

**Comment by helfi92** [comment]
Actually, one moment.

**Comment by helfi92** [comment]
https://github.com/taskcluster/taskcluster/pull/1976

**Pull request merged**
