### PR TITLE
[generic-worker] support uploading object artifacts

### LINKED ISSUE #4605: [generic-worker] Upload artifacts as objects
It's OK to drop the existing s3 upload support, as this will be a major release.

### PR DESCRIPTION
**Pull request by djmitche**
This adds support for uploading artifacts containing data as type 'object' instead of type 's3', still defaulting to 's3'.

The PR begins with some refactoring.  The two interesting bits are adding the new object-service support (which is quite simple, since it relies on existing client support for object-service uploads) and using the configuration value to decide whether to create an S3Artifact or ObjectArtifact.

Github Bug/Issue: Fixes #4605

### CODE REVIEW

**Comment by djmitche** [comment]
I'll need to figure out how to test this in the community instance.  There's really not enough code here to usefully test by mocking out the queue/object services.

**Comment by petemoore** [comment]
@djmitche This looks good so far, but I think the test failures are genuine. Do you want to put it in draft status, until it is ready for review? Thanks!

**Comment by petemoore** [comment]
By the way, the go test failures are best seen by searching for 'FAIL:' in the logs. The failures don't always appear at the end of the log. We could probably change it so that tests exit as soon as one fails...

**Comment by djmitche** [comment]
Looking better now.  I think those tests don't run locally because I don't have credentials locally.

**Review by petemoore — APPROVED** [review]

**Comment by petemoore** [comment]
This looks great, many thanks Dustin!

**Comment by djmitche** [comment]
I merged from main again.  Please merge if successful?

**Comment by lotas** [comment]
Done

**Pull request merged**
