### PR TITLE
Fix: [UI] Deep link the expand scopes view

### LINKED ISSUE #1598: [UI] Deep link the expand scopes view
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**Describe the bug**
It's hard to share links of the expand scopes view without having to re-type the scope.

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/auth/scopes/expansions
2. Type the following in the editor

```
assume:repo:hg.mozilla.org/ci/ci-admin-try:*
assume:project-admin:ateam
```

3. Click the expand scopes button in the lower right
4. Refresh the page

**Actual behavior**
When the user refreshes the page, the editor becomes empty, and the expanded scopes that were displayed after clicking the expand scopes have all been cleared.

**Expected behavior**
When the user refreshes the page, the page looks like before:

Screen Shot 2019-10-13 at 10 31 51 AM

**Additional context**
We can store the editor value as a query parameter and use the [`qs`](https://www.npmjs.com/package/qs) package (already imported in the `ui` directory) to manipulate the query string. We can name the query parameter `scopes` and store it as an array.

### PR DESCRIPTION
**Pull request by shilpiverma509**
Fix #1598 

Bugzilla Bug: [XXXXX](https://bugzilla.mozilla.org/show_bug.cgi?id=XXXXX)

### CODE REVIEW

**Comment by shilpiverma509** [comment]
@helfi92  I have used the query params and saved them in the local state.
Whenever the search param in the location prop has value it will use that to set query paramerters else it will save as an empty string. 
If search param has value it will show the expanded scopes based on that value even after we do a a hard refresh

**Comment by shilpiverma509** [comment]
what do we have to do in the failed case of yarn changelog?

**Comment by JiwoonKim** [comment]
> what do we have to do in the failed case of yarn changelog?

Hi! @shilpiverma509 I had the same issue and solved it just now :)
If I am correct, you should run `yarn changelog --silent --issue 1696`

But since I'm not an expert, maybe @djmitche or @helfi92 can confirm whether this is the right kind of changelog associated with this issue (it could be `minor` or `bug` instead of `silence`)?

**Comment by helfi92** [comment]
`yarn changelog --silent --issue 1696` makes sense to me. Thanks @JiwoonKim.

**Comment by shilpiverma509** [comment]
@JiwoonKim @helfi92  Thankyou. This let me passed the test. Can you guys also review the pr.

**Pull request closed without merging**
