### PR TITLE
renaming all files from .md to .mdx which is present in UI folder

### PR DESCRIPTION
**Pull request by iFlameing**
Bugzilla Bug: [1530790](https://bugzilla.mozilla.org/show_bug.cgi?id=1530790)
I only renamed the folder present in UI folder do I need to rename in the whole repo?

### CODE REVIEW

**Comment by iFlameing** [comment]
@helfi92 I reverted some file name and the above problem is fixed. But I got an awkward error in yarn generate can you take a look please! https://tools.taskcluster.net/groups/at6fZljNRHS_Xdye-4WjWw/tasks/WQb3w3SyTFmyDu3kOH_I3A/runs/0/logs/public%2Flogs%2Flive.log

**Comment by helfi92** [comment]
I wonder if the issue is coming from `https://github.com/taskcluster/taskcluster/blob/91f5d6f77a116feb3e2bf4b7902a3cc839b35fb1/infrastructure/builder/src/generate/generators/docs-tocs.js#L155`. Could you try debugging there?

`yarn generate` runs `docs-tocs.js`. This file builds table of contents for the docs. The error you are seeing tells me that `yarn generate` removed all of the table of contents (probably because it wasn't able to read the files).

**Comment by iFlameing** [comment]
@helfi92 I am getting following error `unexpected command-line arguments` when I am running `yarn generate runs docs-tocs.js`

**Comment by iFlameing** [comment]
@helfi92 I tried doing console.log() but didn't get any response on running yarn generate. How I can debug it?

**Comment by imbstack** [comment]
@iFlameing when debugging `yarn generate`, if you want to do console logging stuff, you can `process.exit()` right after the logging to avoid it getting overwritten. It is a bit of a hack, but it works!

**Comment by arshadkazmi42** [comment]
Sent a new PR here https://github.com/taskcluster/taskcluster/pull/1331

**Comment by djmitche** [comment]
See #1331.

**Pull request closed without merging**
