### PR TITLE
Use curlimages/curl:latest as a docker image with curl

### LINKED ISSUE #4902: docker-worker tests failing
The docker-worker tests began failing a few days ago.  Check pushes to main to see the failures in action.

### PR DESCRIPTION
**Pull request by djmitche**
Github Bug/Issue: Fixes #4902

### CODE REVIEW

**Review by jwhitlock — APPROVED** [review]
Thanks @djmitche! This gets rid of the "pull image failed" messages in the ``docker-worker-chunk-2`` build, even though it doesn't fix it (yet).

**Comment by djmitche** [comment]
Looks like the updated container doesn't have a writeable `/`:
https://community-tc.services.mozilla.com/tasks/g7g14JlrQNa16UHfgf3SRA/runs/0/logs/public/logs/live.log
```
[taskcluster 2021-05-26 18:22:40.284Z] === Task Starting ===
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file /image.tar.zst: Permission denied
  2  748k    2 16018    0     0  31897      0  0:00:24 --:--:--  0:00:24 31844
curl: (23) Failure writing output to destination
[taskcluster 2021-05-26 18:22:41.518Z] === Task Finished ===
```

It might be necessary to add a cache and download it there.

**Comment by jwhitlock** [comment]
The [docs](https://hub.docker.com/r/curlimages/curl) say "To work with files it is best to mount directory:"

```
>  docker run --rm -it -v "$PWD:/work" curlimages/curl -d@/work/test.txt http://httpbin.org/post
```

I don't see a similar need in the [tutum/curl](https://github.com/tutumcloud/curl) image.

I tried reproducing locally, but I wasn't able to get the local install working after a half-hour. I got stuck on the step `vagrant plugin install vagrant-reload`. I may try again after a break.

**Comment by djmitche** [comment]
The local install of docker-worker has never worked for me, for what it's worth.  I've always used push-and-pray debugging.

**Comment by jwhitlock** [comment]
Fixed in PR #4920, with this new docker image plus minor test changes.

**Pull request closed without merging**
