### PR TITLE
Remove userIdFromIdentity utility function

### PR DESCRIPTION
**Pull request by arku**
Removes `utils/userIdFromIdentity.js` and moves the functionality to  `strategies/mozilla-auth0.js` and `strategies/github.js`

Fixes https://github.com/taskcluster/taskcluster/issues/842

### CODE REVIEW

**Comment by helfi92** [comment]
Let me know if there's another issue that you would like to tackle. Happy to help.

**Comment by arku** [comment]
> Let me know if there's another issue that you would like to tackle. Happy to help.

@helfi92 Yeah! That would be awesome!

**Comment by helfi92** [comment]
What do you think about https://github.com/taskcluster/taskcluster/issues/840?

**Comment by arku** [comment]
@helfi92 Sure, feel free to assign it to me.

**Comment by helfi92** [comment]
Check your email or click [here](https://github.com/taskcluster/taskcluster/invitations)] to accept the invitation to become a collaborator. Once accepted, I will be able to assign it to you :)

**Comment by arku** [comment]
@helfi92 Done. Thanks!

**Comment by helfi92** [comment]
Thanks! Assigned :)

**Pull request merged**
