### PR TITLE
Upgrade to Ajv-7.x

### LINKED ISSUE #4133: Upgrade Ajv to 7.x
Continued from #4114 which also has a few commits and some notes.

### PR DESCRIPTION
**Pull request by djmitche**
Github Bug/Issue: Fixes #4133

### CODE REVIEW

**Review by petemoore — APPROVED** [review]
It looks ok to me, but I'd prefer a node expert to look through it, so this is more of a rubber stamp with my eyes closed.

**Comment by djmitche** [comment]
@imbstack was involved with the Ajv work, so a second review from him would be great

**Review by imbstack — APPROVED** [review]
thanks very much. easy to review split into commits and it all makes sense

how did we live without strict mode for so long? way more mistakes than I thought we would end up having

**Comment by djmitche** [comment]
Yeah, it's pretty scary!  We tried valiantly with the metaschema (or as I like to type it, meatschema), but it missed a lot of stuff.

**Pull request merged**
