### PR TITLE
Add title back to every docs page

### PR DESCRIPTION
**Pull request by littlebobby**
Relates to #439.

### CODE REVIEW

**Comment by littlebobby** [comment]
hey, it was my very first contribution. I noticed the docs are generated by `mdx-js` from markdown and its title is not a heading component there, so I hardcoded `h1`  to wrap it. I also declared a variable to hold the doc contents for code readability.

Thanks for reviewing and let me know if I did anything incorrect.

**Comment by littlebobby** [comment]
Thanks for the very detailed instructions @helfi92 :D I checked docs in both places and encountering this problem:
- Docs that have **multiple** `h1` tags but no headers at the top. For example, in [`/services/github/docs/taskcluster-yml-v1.md`](https://raw.githubusercontent.com/taskcluster/taskcluster/master/services/github/docs/taskcluster-yml-v1.md) it has several headers but none of which seems to represent its 'true content'. Could you please provide information on how to handle this case?

Just to recap what you mentioned before:
- Docs need to be added an `h1` tag with its title:
  1. Static docs in `ui/docs/static`.
  2. Dynamic docs in `services/<service-name>/docs`.

- Docs not need to be changed at all:
  1. Any static or dynamic docs not containing header tags. For example, there is no need to add a title for [`/ui/docs/static/manual/design/apis/hawk/clients.md`](https://raw.githubusercontent.com/taskcluster/taskcluster/master/ui/docs/static/manual/design/apis/hawk/clients.md).

**Comment by helfi92** [comment]
> Docs that have multiple h1 tags but no headers at the top. For example, in /services/github/docs/taskcluster-yml-v1.md it has several headers but none of which seems to represent its 'true content'. Could you please provide information on how to handle this case?

I agree, the semantics of this document will need to be changed. For now, you can add an `h1` tag for it and then I will file an issue later to have this document's headers fixed :)

> - Docs need to be added an `h1` tag with its title: 

💯
> - Docs not need to be changed at all:

💯

**Comment by littlebobby** [comment]
#### Docs have one/multiple `h1` tags already
- [`services/github/docs/taskcluster-yml-v0.md`](https://raw.githubusercontent.com/taskcluster/taskcluster/master/services/github/docs/taskcluster-yml-v0.md).
- [`services/github/docs/taskcluster-yml-v1.md`](https://raw.githubusercontent.com/taskcluster/taskcluster/master/services/github/docs/taskcluster-yml-v1.md).
- [`/ui/docs/static/manual/design/devel/best-practices/testing.md`](https://raw.githubusercontent.com/taskcluster/taskcluster/master/ui/docs/static/manual/design/devel/best-practices/testing.md).
- [`/ui/docs/static/manual/using/administration.md`](https://raw.githubusercontent.com/taskcluster/taskcluster/master/ui/docs/static/manual/using/administration.md).

#### Docs have a `h2`/`h3` tag on top originally, so there will be two headers after adding the `h1` title back, which may look not great to users.
- [`/ui/docs/static/manual/using/artifacts.md`](https://raw.githubusercontent.com/taskcluster/taskcluster/master/ui/docs/static/manual/using/artifacts.md).
- [`/master/services/web-server/docs/authentication.md`](https://raw.githubusercontent.com/taskcluster/taskcluster/master/services/web-server/docs/authentication.md). This markdown page has a title before my change.
- [`/ui/docs/static/manual/using/actions/guidelines.md`](https://raw.githubusercontent.com/taskcluster/taskcluster/master/ui/docs/static/manual/using/actions/guidelines.md).
- [`/ui/docs/static/resources.md`](https://raw.githubusercontent.com/taskcluster/taskcluster/master/ui/docs/static/resources.md).

_I lists the docs that may still need amendments for future references, so there is no need to go through all the files again :D_

**Pull request merged**
