### PR TITLE
Bug 1551607 - let docker networks settle before doing anything

### PR DESCRIPTION
**Pull request by djmitche**
Bugzilla Bug: [1551607](https://bugzilla.mozilla.org/show_bug.cgi?id=1551607)

### CODE REVIEW

**Comment by helfi92** [comment]
I'm not able to run `yarn build` on latest master for some reason:

```bash
➜  taskcluster git:(master) yarn build
yarn run v1.16.0
$ node infrastructure/builder/src/main.js build
... 2 completed tasks
✖ Clone Monorepo from Working Copy (Error: Command failed: git rev-parse HEAD
fatal: Not a git repository (or any of the parent directories): .git
)
50% finished
{ Error: Command failed: git rev-parse HEAD
fatal: Not a git repository (or any of the parent directories): .git

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 128,
  signal: null,
  cmd: 'git rev-parse HEAD',
  stdout: '',
  stderr:
   'fatal: Not a git repository (or any of the parent directories): .git\n' }
```

**Comment by djmitche** [comment]
That's a new one!  Is that reproducible?  I don't see the same, even if I run `yarn build` in the `.git` directory.

However, I have Git 2.21.0 which has a different error message for that situation, so at a guess (a) you're using an older version of Git and (b) you ran `yarn build` in the `.git` directory?

That command is just run on the host -- no Docker involved.  So if this is an OS issue, we might need to just get you and owlish laptops with a functional OS ;)

**Comment by helfi92** [comment]
> That's a new one

Agreed.

```bash
➜  taskcluster git:(master) git --version
git version 2.21.0
➜  taskcluster git:(master) yarn
yarn install v1.16.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.59s.
➜  taskcluster git:(master) yarn build
yarn run v1.16.0
$ node infrastructure/builder/src/main.js build
... 2 completed tasks
✖ Clone Monorepo from Working Copy (Error: Command failed: git rev-parse HEAD
fatal: not a git repository (or any of the parent directories): .git
)
50% finished
{ Error: Command failed: git rev-parse HEAD
fatal: not a git repository (or any of the parent directories): .git

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 128,
  signal: null,
  cmd: 'git rev-parse HEAD',
  stdout: '',
  stderr:
   'fatal: not a git repository (or any of the parent directories): .git\n' }
error Command failed with exit code 1.
```

**Comment by helfi92** [comment]
> I'll try pulling a fresh clone of taskcluster and see if that works.

That didn't work.

**Comment by djmitche** [comment]
[This code](https://github.com/git/git/blob/6a6c0f10a70a6eb101c213b09ae82a9cad252743/setup.c#L665) generates that error message, called from [here](https://github.com/git/git/blob/6a6c0f10a70a6eb101c213b09ae82a9cad252743/setup.c#L764).  These seem to be about work trees and possibly GIT_.. env vars.  Do you have any of those set?  Does `git rev-parse HEAD` work if run in the current directory?

**Comment by helfi92** [comment]
> Does git rev-parse HEAD work if run in the current directory?

```bash
➜  taskcluster git:(master) git rev-parse HEAD
95c164374dc1952505f106180efe240e92cbf004
```

**Comment by djmitche** [comment]
What the heck?  That bit hasn't even changed recently.

Can you try running it under `dtruss` (https://opensourcehacker.com/2011/12/02/osx-strace-equivalent-dtruss-seeing-inside-applications-what-they-do-and-why-they-hang/) and sending the trace (it will be huge and may contain secrets) to me privately?

**Comment by helfi92** [comment]
```bash
➜  taskcluster git:(master) sudo chmod u+s /usr/sbin/dtrace
chmod: Unable to change file mode on /usr/sbin/dtrace: Operation not permitted
➜  taskcluster git:(master) sudo dtruss yarn build
dtrace: system integrity protection is on, some features will not be available

dtrace: failed to execute yarn: dtrace cannot control executables signed with restricted entitlements
```

**Pull request closed without merging**
