### PR TITLE
Issue 4765 - native darwin/arm64 release binaries

### LINKED ISSUE #4765: Provide native darwin/arm64 builds of release binaries
Provide the following additional release binaries for native apple silicon support:

* `generic-worker-multiuser-darwin-arm64`
* `generic-worker-simple-darwin-arm64`
* `livelog-darwin-arm64`
* `start-worker-darwin-arm64`
* `taskcluster-darwin-arm64`
* `taskcluster-proxy-darwin-arm64`

This is possible for the first time since we upgraded to go 1.16 in #4743.

### PR DESCRIPTION
**Pull request by petemoore**
Github Bug/Issue: Fixes #4765

### CODE REVIEW

**Review by djmitche — APPROVED** [review]
Looks good!  You might want to run a staging release after landing just to check that these build correctly, but chances are good that it will be fine.

**Comment by petemoore** [comment]
> Looks good! You might want to run a staging release after landing just to check that these build correctly, but chances are good that it will be fine.

Good idea!

I've pushed a staging release here: https://github.com/taskcluster/staging-releases/tree/staging-release/v43.2.0

**Comment by djmitche** [comment]
Looks like it worked!

**Comment by davehouse** [comment]
generic-worker-simple-darwin-arm64 is missing. Can this be added for future releases?
image

**Pull request merged**
