### PR TITLE
remove now-redundant-and-incorrect logging about error

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by djmitche** [comment]
Failing queue check is https://bugzilla.mozilla.org/show_bug.cgi?id=1525444

**Comment by djmitche** [comment]
> I'm wondering if this is some hold-over from the sentry days?

I think so, yeah -- I spotted it in a log a while ago and was confused

**Comment by owlishDeveloper** [comment]
I understand this is redundant and incorrect after we've moved to the structured logging?

**Comment by djmitche** [comment]
Yes -- it made sense when still using sentry.

**Comment by owlishDeveloper** [comment]
`this.monitor.reportError` doesn't go to Sentry anymore, goes to regular logs (where the `debug` used to go)?

**Comment by djmitche** [comment]
Yes, and that ends up in the GCP errors display (that's replacing sentry)

**Comment by djmitche** [comment]
@owlishDeveloper is this OK to land?

**Comment by owlishDeveloper** [comment]
Yes!

**Pull request merged**
