### PR TITLE
Changed Colour Of Selection Text

### PR DESCRIPTION
**Pull request by Anubhavshakya**
Changed Colour Of Selection Text with a minimum Opacity for the theme.

### CODE REVIEW

**Comment by Anubhavshakya** [comment]
Yes, We shall see...

**Comment by helfi92** [comment]
@Anubhavshakya Do you mind adding me as a collaborator to `Anubhavshakya/taskcluster`. You can do that by navigating to the repo -> settings -> collaborators.

**Comment by helfi92** [comment]
@Anubhavshakya Nevermind, you just have to click the "Allow edits from maintainers" button as shown in https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork.

**Comment by Anubhavshakya** [comment]
yes, why not.
Done.

**Comment by Anubhavshakya** [comment]
I ticked the option "Allow edits from maintainers"

**Comment by helfi92** [comment]
Here's a preview link: https://deploy-preview-410--taskcluster-web.netlify.com/

**Comment by Anubhavshakya** [comment]
Now Site looking great. Because the colour of the link is the same in docs and the main site.

**Comment by helfi92** [comment]
> Now Site looking great. Because the colour of the link is the same in docs and the main site.

Awesome. Thank you for your work!!

**Pull request merged**
