### PR TITLE
[WIP][UI] Colour accessible favicons

### LINKED ISSUE #306: New UI: Success/failure colour in favicon is too small
Trying to notice the status of a TC build job from the icon is much harder now with the new UI's icon.

Could this be made bigger and with [more accessible colours](https://en.wikipedia.org/wiki/Color_blindness#Deuteranopia)?

screen shot 2019-02-25 at 3 21 36 pm

### PR DESCRIPTION
**Pull request by projectyang**
Fixes #306 

Changed favicon status indicator from coloured squares to coloured icons to help with accessibility.

Icon SVG sources:
N/A (original)
logo
logoCompleted
logoRunning
logoFailed

Preview:
Screen Shot 2019-04-25 at 1 34 59 PM
Screen Shot 2019-04-25 at 1 35 58 PM
Screen Shot 2019-04-25 at 1 34 03 PM

Dark mode:
Screen Shot 2019-04-25 at 1 34 52 PM
Screen Shot 2019-04-25 at 1 35 37 PM
Screen Shot 2019-04-25 at 1 34 22 PM

### CODE REVIEW

**Comment by djmitche** [comment]
I like these!  A tiny detail though: the checkmark has a shadow, while the others do not.  For simplicity of appearance, it probably makes sense for none of them to have shadows..

**Comment by djmitche** [comment]
Maybe ▷?

**Comment by projectyang** [comment]
Updated! Thanks for the suggestions.

**Comment by projectyang** [comment]
> Overall, I think this is a big improvement over what we currently have :) A couple of things:
> 
> * The "x" and "✓" icons don't sit well with the ">" icon in my opinion. I think it's because they have curvatures in them whereas the ">" icon has no curves.
> * The status icons are too close to the "T" symbol.
> 
> Let me know what you think of the following sketch:
> 
> Screen Shot 2019-04-21 at 5 47 30 PM
> 
> Screen Shot 2019-04-21 at 5 33 42 PM
> 
> Screen Shot 2019-04-21 at 5 44 24 PM

Nice, very clean. I'll make the adjusted changes for the PNGs.

**Comment by helfi92** [comment]
I can send you the svg sketches of the statuses. What email do you want me to send it to?

**Comment by projectyang** [comment]
Jasonjyang1@gmail.com 

Thanks!

**Comment by projectyang** [comment]
Made the adjusted style changes, looking better and better. :)

**Comment by projectyang** [comment]
> Nice! I love the running and failed states icons. I'm not too sure about the completed state however. The rotation and positioning feels a bit off. Instead of
> Screen Shot 2019-04-23 at 8 38 58 PM
> 
> let's try to make it look more like
> 
> Screen Shot 2019-04-21 at 5 33 42 PM
> 
> Looking forward to having this merged soon!

Gotcha. Adjusted the positioning of the checkmark + raised icon cutoff for all states a tad higher to compensate. Also slightly modified the colour of the checkmark. (See updated screenshots above).

**Comment by projectyang** [comment]
Added more buffer for logoCompleted:
Screen Shot 2019-04-24 at 3 06 45 PM

Couple points:

- Do you want me to adjust the T width as well? (based on your sketch, the T doesn't take up the entire frame)

- The PNG size is 320x400 (as per the original logo.png). Scaling it down to 32x32 messes up the ratios (e.g. 32x40 vs 32x32). If it's not affecting any compatibility issues, maybe we can consider leaving the size as is?:
Screen Shot 2019-04-24 at 3 06 01 PM

**Comment by projectyang** [comment]
Ah, I see. Apologies for making the mistake in the original favicon implementation. 

I realize I should've just used your provided SVGs....instead of wasting time editing the ones I had. I'll just make the naming adjustments to yours then?

**Comment by helfi92** [comment]
No worries at all :)

> I'll just make the naming adjustments to yours then?

Sounds good to me.

**Comment by projectyang** [comment]
Updated with screenshots. Just to note - the default logo favicon is slightly cut off at the bottom compared to the full 320x400 PNG (this is to maintain ratios relative to the others and the 32x32 requirement)

**Comment by helfi92** [comment]
@projectyang Do you mind sending me the SVG assets, please? It would be nice to have a copy of them :)

**Comment by djmitche** [comment]
Woo!  Long process with a great outcome :)

> @projectyang Do you mind sending me the SVG assets, please? It would be nice to have a copy of them :)

https://github.com/taskcluster/taskcluster-media would be a good spot

**Comment by helfi92** [comment]
Agreed, taskcluster-media would be the right place for that :)

**Comment by projectyang** [comment]
Sent you an email Hassan with the SVGs. :)

Went ahead and created a pull request as well on taskcluster-media for adding them in.

**Pull request merged**
