### PR TITLE
Implementation of Shareable Links #1398

### LINKED ISSUE #1398: "Compare Scopesets" and "Expand Scopesets" should have a linkable URL
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

When working with scopes in a chat conversation, it would be useful to be able to link to these two tools with their values filled in already.  For example, I should be able to enter some scopes into the Scope Expander, click expand, and then copy the URL bar and paste it into a chat.  Currently, the URL does not change.

### PR DESCRIPTION
**Pull request by mkneumann777**
"Compare Scopesets" and "Expand Scopesets" should have a linkable URL.

Fixes #1398.

### CODE REVIEW

**Comment by helfi92** [comment]
Note: I think we will wait until https://github.com/taskcluster/taskcluster/pull/1729 is merged before merging to avoid code conflicts.

**Comment by mkneumann777** [comment]
Most excellent! I learn quite a lot fixing this issue/bug. I particularly enjoyed working with the packages/libs to implement clean and uniform code with `qs`, `parse` and `stringify`. Also, I wasn't aware that `this.setState` makes a performance hit within the `componentDidMount()` lifecycle method. The course I'm taking on React.js didn't mention this when covering the subject.

So what happens next? Should I wait to log this as a contribution to my Outreachy application until it is fully merged?

**Comment by helfi92** [comment]
Please go ahead and add this contribution to your Outreachy application :)

**Comment by helfi92** [comment]
@all-contributors please add @mkneumann777 for code.

**Pull request merged**
