### PR TITLE
Cloudops refactor of deployment

### PR DESCRIPTION
**Pull request by edunham**
https://bugzilla.mozilla.org/show_bug.cgi?id=1546801 kind of related

* Haven't cleaned up the history
* PRs at https://github.com/sciurus/taskcluster/pulls are on their way into this too

### CODE REVIEW

**Comment by edunham** [comment]
cloudops todo: 
 - [ ]  sample Values stuff 
 - [ ]  fix up README
 - [ ] land notify
 - [ ]  decide whether to fix up services first before landing or no

**Comment by imbstack** [comment]
@edunham @sciurus what do you two think about landing whatever outstanding PRs you have to this, landing it now, and handling the rest of the TODOs in a separate PR? I'd love to have this in the repo now so that I can start trying to use it for tc internal stuff!

If that is not worth the effort I'm also happy to let this wait until ready as well.

**Comment by sciurus** [comment]
@imbstack I think although there will be some tweaks here and there, this is basically done. No objection sfrom me for merging. It's really up to how you want to approach this. Merging this will break your existing dev environments, but you can have them reference an older release of this repo when they pull in your terraform module.

**Comment by sciurus** [comment]
Let's close this in favor of https://github.com/taskcluster/taskcluster/pull/945

**Pull request closed without merging**
