### PR TITLE
[UI] Task group list enhancement

### LINKED ISSUE #245: New UI: can't search for a task in task group list
When you have thousands of tasks in a group, like in https://taskcluster-web.netlify.com/tasks/groups/OedTF0wpS6Cg_AJUpFdcvw, you can't search in the page to find the task you'd be looking for, because not all tasks are actually in the page from the browser's perspective.

### LINKED ISSUE #247: New UI: can't scroll task group list with keyboard

### PR DESCRIPTION
**Pull request by helfi92**
Fixes #247.
Fixes https://github.com/taskcluster/taskcluster/issues/231.

### CODE REVIEW

**Comment by helfi92** [comment]
@djmitche It'd be great if you can look at https://deploy-preview-264--taskcluster-web.netlify.com/tasks/groups/PgWC0mATSSSElyJGFRFAfw and see if the UX is improved. The code is somewhat of a hack but it does the trick.

**Comment by owlishDeveloper** [comment]
Issue #245 is not fixed for me. Scrolling works good.

(I added myself to frontend reviewers because I have 1 year of experience developing a React-Redux application, so if it's not something taskcluster-specific - most of the time I will able to review)

**Comment by helfi92** [comment]
> Issue #245 is not fixed for me.

Sorry, that was the wrong issue. I edited my first comment to point to the right one: https://github.com/taskcluster/taskcluster/issues/231

**Comment by owlishDeveloper** [comment]
oic 

So I looked at the page on a 1920x1200 monitor - LGTM in FF and Chrome (I don't presume they use Chrome all that much tho lol). I also tried zooming out and Empy Cahche + Gard Reload - LGTM

**Comment by owlishDeveloper** [comment]
PS - I tried clicking the link the user left in the issue on that same monitor - the reproduced for me. So I think this PR fixes it.

**Comment by djmitche** [comment]
lgtm too

**Pull request merged**
