### PR TITLE
Implement method negotiation in the downloadObject API endpoint

### PR DESCRIPTION
**Pull request by djmitche**
..and fix a few other minor inconsistencies in the API endpoint.

This was some preparatory work I did for #3931, and I thought I'd put it up for review while I work on the rest of that issue.

### CODE REVIEW

**Comment by djmitche** [comment]
I'll rebase this since the `yarn generate` stuff conflicts, but feel free to review anyway :)

**Comment by djmitche** [comment]
I'll take anyone's review :)

**Review by jwhitlock — APPROVED** [review]
@djmitche Thanks, the changes look good. Only the metadata test fails, and I agree that a changelog entry is not needed. 

The biggest change appears to be ``protocol`` to ``method``. I've seen (and participated) in discussions about that name, ``method`` is a decent choice and looks good when used in code.

**Comment by djmitche** [comment]
I think this just changed one or two leftover uses of "protocol", leaving the majority at "method".  Consistent, at least :)

**Pull request merged**
