### PR TITLE
Update Node.js from 14.17.15 to 16.13.2 LTS

### PR DESCRIPTION
**Pull request by jwhitlock**
Update Node.js from 14.17.15 to 16.13.2, the [LTS version](https://nodejs.org/en/about/releases/) until 2022-10-18.

This was originally part of PR #5084, where it failed on the ``docker-worker-chunk-X`` steps. These (mostly) pass after updating the `worker-ci` image from Ubuntu 14.04 to 20.04, which also includes:

* Updating from Docker 18.06.3 to 20.10.12
* Implementing a new method for registering the Docker package repo
* Switch from GZip to the XZ-compressed Node.js package

### CODE REVIEW

**Comment by jwhitlock** [comment]
This is a new one - I haven't seen the decision task fail before. We did recently update it to get the Python 3 version. I'll try again in the morning.

**Comment by jwhitlock** [comment]
Ah, found it - a poorly encoded special quote character in the commit message:

```
> change in behavior, and it’s still possible to switch modes using the
```
This showed up as the byte sequence `\xe2\x80\x99`. I changed it to:
```
> change in behavior, and it's still possible to switch modes using the
```

**Comment by jwhitlock** [comment]
I added a commit that updates the `worker-ci` image to Ubuntu 20.04, and I've pushed the new image to the `node16.13.2` tag (which continues to be used by just these node update PRs). 4 of the 5 `docker-worker-chunk-X` tests passed, and `docker-worker-chunk-2` had one failing test, the `cat stress test`:

https://github.com/taskcluster/taskcluster/blob/af2ac88f8466363b1d296b751af8160c487a1807/workers/docker-worker/test/integration/interactive_test.js#L226

I'm trying again (making a small change to the commit message and force pushing), since it looks like it is sensitive to timing.

**Review by lotas — APPROVED** [review]
:+1:

**Comment by jwhitlock** [comment]
The same test failed on a re-run, so I think this is a real regression. I find it very challenging to determine what is happening in the build step. I'm inclined to disable the test and work on it in a new PR, since everything else is working. However, this could be demonstrating something in Node 16.12.2, or Ubuntu 20.04, that will impact other CI jobs.

I think my next attempt will be to add a new CI step that just runs this test, to help with debugging and remove other distractions. I'll work on that Monday.

**Comment by jwhitlock** [comment]
Made some progress.

The test is waiting forever on this line:

https://github.com/taskcluster/taskcluster/blob/af2ac88f8466363b1d296b751af8160c487a1807/workers/docker-worker/test/integration/interactive_test.js#L259

I noticed that this test was similar but different from one labelled "cat". Most importantly, this is the only test that uses `DockerExecClient` from `docker-exec-websocket-client`. Which is a SysEng project - https://github.com/taskcluster/docker-exec-websocket-client. All the tests in that project pass on Node.JS v14.17.5, but one fails on v16.13.2. AND, I can run those tests locally rather than push to community-ci.

I filed https://github.com/taskcluster/docker-exec-websocket-client/issues/1, and will try to get that working.

**Comment by jwhitlock** [comment]
After a lot of work, I found and fixed an issue in https://github.com/taskcluster/docker-exec-websocket-server/pull/35. A few steps are needed:

* [ ] Review and merge docker-exec-websocket-server PR 35
* [ ] Release a new version of docker-exec-websocket-server
* [ ] Update https://github.com/taskcluster/docker-exec-websocket-client/pull/2 to use that version, get passing tests
* [ ] Review and merge docker-exec-websocket-client PR 2
* [ ] Release a new version of docker-exec-websocket-client
* [ ] Rebase and update this PR to use both, get tests to pass

**Comment by jwhitlock** [comment]
With the 3.0.0 versions of `docker-exec-websocket-client` and `docker-exec-websocket-server`, the `cat stress test` is still failing, but no longer stuck waiting for the `Promise`. Now it is failing because the output does not match the input. I'll debug in the morning.

**Comment by jwhitlock** [comment]
As discussed at https://github.com/taskcluster/taskcluster/pull/5154#issuecomment-1033022576, the problem was that the output _does_ match the input, but it didn't before... The test now passes under Node v14, and this is rebased to include the `docker-exec-websocket-*` libraries and the corrected test.

**Comment by jwhitlock** [comment]
So far one error that looks like an intermittent. In `service-secrets`, the tests passed, but [failed to upload the coverage report](https://community-tc.services.mozilla.com/tasks/eXBn6rCFS7WB82Wid9uqVw/runs/0/logs/public/logs/live.log#L100):

```
[taskcluster:error] Error uploading "public/coverage-final.json" artifact. getaddrinfo EAI_AGAIN community-tc.services.mozilla.com
```

I could re-run, but I think its ready to merge.

**Review by matt-boris — APPROVED** [review]
LG(reat)TM! Thanks John for this huge effort right as you're transitioning off the team. This is awesome. 👏🏻 🎉

**Comment by matt-boris** [comment]
Lol v16.14.0 was just released 😂

**Comment by jwhitlock** [comment]
The diff doesn't show that there was a huge effort, which is how it should be for most Node updates. I hope the 16.14.0 is just a matter of following the docs!

**Pull request merged**
