### PR TITLE
Fix Taskcluster shell linux binary download link

### PR DESCRIPTION
**Pull request by arku**
Removes the stray `"` from the download link.

### CODE REVIEW

**Comment by arku** [comment]
@djmitche Just curious, is there a way to skip Taskcluster builds with a special commit message (that starts with `[skip ci]` or something like that)?

**Comment by imbstack** [comment]
@arku This actually won't fix this. This line is generated in [infrastructure/builder/src/release/tasks.js](https://github.com/taskcluster/taskcluster/blob/master/infrastructure/builder/src/release/tasks.js#L141)

There's no way to skip building but we like it that way! It's not a waste of resources or anything.

**Comment by arku** [comment]
@imbstack Ah, my bad.

Let me fix it.

**Comment by arku** [comment]
@imbstack I am having a hard time testing my fix (running into `spawn ENOENT` errors). How do I go about it?

**Comment by imbstack** [comment]
@arku that's ok. `yarn release` is really hard to test. This looks correct to me! I'll land it as soon as tests complete.

Thanks for the fix.

**Comment by arku** [comment]
@imbstack Perfect, thanks!

**Pull request merged**
