### PR TITLE
Mobile menu creation

### PR DESCRIPTION
**Pull request by Soundharyaam**
**Issue:**

The entities/icons on the right side of the search box breaks in the mobile-view. 

**Steps that are taken to resolve this issue:**

New `<MobileMenu/>` component has been created for displaying the menu in the mobile-view.

**Before bug fix:**

66474700-6f5c3100-eaaf-11e9-842f-77d8da36a47b

**After bug fix:**

https://imgur.com/9JIcDBO

### CODE REVIEW

**Comment by Soundharyaam** [comment]
**Scenarios to consider/think about for the next round:**

- Do we need to display the `theme toggle` in mobile-view? As of now, I have not included it. If we have to include, what's the breakpoint width that has to be considered for this?
- Options like `Account` and `Sign In/Sign Out` has been shown directly into the `VerticalDotsIcon` drop-down menu. Over here, do we need to display the user-name at first drop-down and place other-two options of `Account` and `Sign In/Sign Out` under this? This will increase the tediousness of the User experience since the space in the mobile-view less compared to the web-view. 
- When we click on the `Account` Option, it's going to the root link at first click and on the second-click, it's going to the `/profile` route. It's happening in the web-view too. So, we gotta find a solution to this. The heading is also different over here- `Profile` is being used as the heading. 
- The active tab is not being displayed properly. When I click on the Account option, the active tab is not getting rendered properly. I am working on this already.
- Is there any extra scenario that we have to consider to check `sign-in/sign-out` options?

These are the issues that I will be focusing on next. Please do let me know, what's your thoughts on this? @helfi92 @djmitche 

If I find something else, I will add it over here.

**Comment by Soundharyaam** [comment]
**To dos:**

- [ ] Move the vertical dots icon to the right corner. Now it's displaying near the search box. If the light theme is selected, the icon color should not change.
- [ ] The active tab should be selected properly.
- [ ] `Account` page routing should happen properly.

**Comment by helfi92** [comment]
> These are the issues that I will be focusing on next. Please do let me know, what's your thoughts on this? @helfi92 @djmitche

Makes sense to me.

**Comment by helfi92** [comment]
Let me know if you had questions for me.

**Comment by Soundharyaam** [comment]
Sure. Thanks @helfi92.

**Comment by Soundharyaam** [comment]
> If you rebase your changes onto the latest master, it will avoid that error message. Sorry about that!

@djmitche Thanks for letting me know this. Can I do that once I am done with all the tasks?

**Comment by Soundharyaam** [comment]
@helfi92 When we click on the `Account`, it should redirect to root `http://localhost:5080/` or `http://localhost:5080/profile`?

**Comment by helfi92** [comment]
http://localhost:5080/profile

**Comment by Soundharyaam** [comment]
@helfi92 Thank you. As I pointed out before, 

> When we click on the Account Option, it's going to the root link at first click and on the second-click, it's going to the /profile route. It's happening in the web-view too. So, we gotta find a solution to this. The heading is also different over here- Profile is being used as the heading.

Can you please let me know, where should I make a change for this?

**Comment by helfi92** [comment]
> When we click on the Account Option, it's going to the root link at first click and on the second-click, it's going to the /profile route. It's happening in the web-view too. So, we gotta find a solution to this. The heading is also different over here- Profile is being used as the heading.

Hm, I'm not able to replicate. It seems like it's working for me. What browser are you using? Does it work if you use a different browser?

**Comment by Soundharyaam** [comment]
> > When we click on the Account Option, it's going to the root link at first click and on the second-click, it's going to the /profile route. It's happening in the web-view too. So, we gotta find a solution to this. The heading is also different over here- Profile is being used as the heading.
> 
> Hm, I'm not able to replicate. It seems like it's working for me. What browser are you using? Does it work if you use a different browser?

@helfi92 Hi, I kinda found it. This behavior is happening, when we click on the `Documentation` link and then move to the `Account`. If we directly go to the `Account`, it's not happening. I checked it in chromes and firefox. How should I proceed with this one?

**Comment by Soundharyaam** [comment]
@helfi92 Thanks for the feedback. I am working on this.

**Comment by helfi92** [comment]
> This behavior is happening, when we click on the Documentation link and then move to the Account. If we directly go to the Account, it's not happening. I checked it in chromes and firefox. How should I proceed with this one?

I'm still not able to replicate. Perhaps you can share a gif video or something. Otherwise, feel free to work on the comments of the previous review then we can look into this issue after. Let me know when it's ready for review.

**Comment by Soundharyaam** [comment]
Hi @helfi92,

> I'm still not able to replicate. Perhaps you can share a gif video or something. Otherwise, feel free to work on the comments of the previous review then we can look into this issue after. Let me know when it's ready for review.

In the gif, which I attached earlier, you can find this happening: https://imgur.com/9JIcDBO.

> When we're not showing the search bar, we should keep the same current behavior (i.e., show all buttons). 

I have added the `verticalDotsIcon` for this as well, which will be comprised of `Documentation` and `Sign In` link since the spacing issue will again arise if we include the options in a single line and making the `verticalDotsIcon` everywhere would be consistent throughout. Let me know about this. If you want, we can change this as well. But, over here, I couldn't make the `sign in` modal to open. 
I am getting the error as: 
```
The prop `onClose` is marked as required in `SignInDialog`, but its value is `undefined`.
```

Could you help me with this one?

**Comment by helfi92** [comment]
> I am getting the error as:
> 
> ```
> The prop `onClose` is marked as required in `SignInDialog`, but its value is `undefined`.
> ```
> 
> Could you help me with this one?

The error is saying that `SignInDialog` expects an `onClose` method (e.g., `<SignInDialog onClose={...} />` but right now it's not getting this. One thing you can do is use `console.log` to see why this prop is not defined.

**Comment by helfi92** [comment]
Let me know if you had questions or whether this is ready for review.

**Comment by helfi92** [comment]
Someone is working on https://github.com/taskcluster/taskcluster/issues/1747 so no need to fix the navigation issue here :)

**Comment by helfi92** [comment]
@all-contributors please add @Soundharyaam for code

**Comment by Soundharyaam** [comment]
> Someone is working on #1747 so no need to fix the navigation issue here :)

Okay @helfi92

**Comment by helfi92** [comment]
@Soundharyaam Is this ready for review?

**Comment by Soundharyaam** [comment]
@helfi92 Hi, It's ready for the review.

**Comment by vishakhanihore** [comment]
@helfi92 @djmitche  Just a suggestion, According to me, Since we only have 2 options in our nav-bar, The previous style was already awesome.
This PR not only results in 246 lines of duplicated code from `UserMenu.jsx` but also showing a mobile toggle just for two options won't make sense where we can easily accommodate them in the navbar.
**See the current Taskcluster nav-bar: **
Screenshot 2019-11-01 at 8 21 01 PM
We beautifully show the Page name and all the icons seems nicely arranged.

But after this PR  : 
Screenshot 2019-11-01 at 8 22 04 PM
- Upper page title name is missing.
- I need to click on the toggle to visit documentation, which doesn't seem required as of now.

**Comment by helfi92** [comment]
@vishakhanihore The issue we are trying to fix is https://github.com/taskcluster/taskcluster/issues/1670#issue-508399706.

**Comment by Soundharyaam** [comment]
> I have added the verticalDotsIcon for this as well, which will be comprised of Documentation and Sign In link since the spacing issue will again arise if we include the options in a single line and making the verticalDotsIcon everywhere would be consistent throughout.

1. As I said earlier, I have implemented the above scenario cause of the spacing issues which we faced earlier. If we do this, again the spacing problems may arise.

2 & 3. I will look at it.
4. Do we need that option in the mobile view, necessarily, as I previously asked? 
5. When we click on the `Information` icon, we see some Description as `Manage roles on Auth service. This tool allows you to create, modify, and delete roles. You can also manage scopes and explore indirect scopes.` on the right side. I don't know whether it's much needed in the mobile view. Also, the user-space is very less over here. So, we gotta utilize it properly. Lemme know, what're your thoughts?

@helfi92

**Comment by helfi92** [comment]
> 4. Do we need that option in the mobile view, necessarily, as I previously asked?
> 5. When we click on the `Information` icon, we see some Description as `Manage roles on Auth service. This tool allows you to create, modify, and delete roles. You can also manage scopes and explore indirect scopes.` on the right side. I don't know whether it's much needed in the mobile view. Also, the user-space is very less over here. So, we gotta utilize it properly. Lemme know, what're your thoughts?

Yes, I think we should provide the same features for both mobile and desktop to reduce confusions with users.

**Comment by Soundharyaam** [comment]
@vishakhanihore First, without knowing the primary problem, don't try to criticize other people's work. As @helfi92 said, we are trying to solve something else that you literally don't have any idea. And, this is not the duplicated code, I have spent most of the time scrutinizing what has to be done in the better and efficient way, that's why I have removed one complete MobileMenuButton component completely today. And, instead of peeking at my code and finding something to work for, find some really serious problem and work on its the solution, like others. As always, good luck. That would be good for your career as well.

**Comment by Soundharyaam** [comment]
> > 1. Do we need that option in the mobile view, necessarily, as I previously asked?
> > 2. When we click on the `Information` icon, we see some Description as `Manage roles on Auth service. This tool allows you to create, modify, and delete roles. You can also manage scopes and explore indirect scopes.` on the right side. I don't know whether it's much needed in the mobile view. Also, the user-space is very less over here. So, we gotta utilize it properly. Lemme know, what're your thoughts?
> 
> Yes, I think we should provide the same features for both mobile and desktop to reduce confusions with users.

If so, how the point number 5 should be implemented? The same way from the right side?

**Comment by vishakhanihore** [comment]
If you can't see duplicated code, my friend I am sorry you need to learn a
lot . Also, its your choice to see the suggestion as criticism or advice.
Anyway its open source, always value other people opinions it will help you
a lot in future. Not to mention you didnt see the flaw I mentioned in my
comment. Rather you took the suggestion as criticism. Improve the way of
seeing the FOSS , will help you in your career if its not already done.

**Comment by Soundharyaam** [comment]
How do you maintain consistency throughout the app then, if you don't create the component like the way before? Difference between criticism and advice, which everyone knows. Even a layman can find it from your comment since the first moment you started writing the same comment everywhere in my other PRs. I am not here to address your toxicity. I am here for doing something useful. Your comments will not be addressed in my PR from now on. @helfi92 @djmitche Please take some useful actions since this has been happening for the second time.

**Comment by vishakhanihore** [comment]
I dont count micro PRs as PRs. Had there been codacy, your PR would have
easily graded.
Anyway, I don't want to waste my time since you have nothing useful to say
rather than blaming me for your own actions.
Also since you are a contributor too, I request you to show some decency
and courtesy with your collaborators and co-devs. Such attitude and blaming
will take you no where, in open source we collaborate and contribute by
identifying other's mistakes and correcting our own mistakes too. But I
dont think you want to listen to your co-devs rather than code maintainers.
I dont know if open source is your passion or not.But i would surely
recommend you to be humble as much as you can , because being humble is the
number 1 rule for contributing to FOSS.
@djmitche @helfi92 Since you are my mentors and also the project
maintainers, I kindly request you to see there is any issue in my review
comment. Thanks

**Comment by Soundharyaam** [comment]
If someone reads the previous convo which happened over here or in other PRs of mine, anyone can understand who's being humble and trying to solve the issues and who's blaming other person for their work, very easily.

**Comment by helfi92** [comment]
Just a reminder that Taskcluster is governed by the [Mozilla CPG](https://www.mozilla.org/en-US/about/governance/policies/participation/).  I'm going to lock this thread for now.

**Comment by djmitche** [comment]
(closing as stale)

**Pull request closed without merging**
