### PR TITLE
Fix - run go mod tidy in yarn generate

### LINKED ISSUE #1122: Run 'go mod tidy' in yarn generate
`go mod tidy` seems to do a good job of cleaning out the cruft that other `go` tools put into `go.mod` and `go.sum`.  Let's run that command in both `clients/client-go` and `clients/client-shell` on every `yarn generate` run.

It will also be useful to add that command to the [renovate config](https://renovatebot.com/docs/configuration-options/#gomod).

### PR DESCRIPTION
**Pull request by rbrishabh**
Fixes #1122 

Hey @djmitche !

This is a PR to begin the discussion with. 

From [this](https://github.com/taskcluster/taskcluster/issues/1122#issuecomment-516063302) comment:

> 
> In fact most of the code to write would be in JS under `infrastructure/builder/src/generate`, so maybe! But start by getting the `clients/client-go` and `clients/client-shell` tests to run -- in other words, get a working go development environment up and running.

I think the changes I have made are somewhere near what was expected. I couldn't really correctly understand what the method ```execCommand``` expects me to send in the object, so I might be wrong with the approach.

And yes, I was able to set up go development and run the tests, but ```yarn generate``` seems to fail at certain percentages with a different error example [this](https://pastebin.com/ehCDQPXr).

From [this](https://github.com/taskcluster/taskcluster/issues/1122#issue-474028101) comment,
> 
> It will also be useful to add that command to the [renovate config](https://renovatebot.com/docs/configuration-options/#gomod).

How do I add the command to renovate config?

Thanks!

### CODE REVIEW

**Comment by rbrishabh** [comment]
Even after passing ```utils```, this seems to be failing for some reason.

I tried to read the [logs ](https://tools.taskcluster.net/groups/N8gKiowZSGC9teVSN_GdIw/tasks/T9zvkvvRQCuAwv2DY_ObPg/runs/0/logs/public%2Flogs%2Flive.log), but couldn't understand what's missing/wrong.

**Comment by djmitche** [comment]
Did you run `yarn generate` locally and check in the changes it makes?  The logs look like the result of running `go mod tidy`.

**Comment by rbrishabh** [comment]
This the error I get when I run `yarn generate` locally - 

```
86% finished
{ Error: Command failed: node src/main generateReferences

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node src/main generateReferences',
  stdout:
   'Error: v1\\pulse-job.json: schema.$id should match format "uri-reference"; v1\\task-treeherder-config.json: schema.$id should match format "uri-reference"\n    at exports.validate (C:\\Users\\Rishabh\\Desktop\\firefox\\taskcluster\\taskcluster\\libraries\\references\\src\\validate.js:273:11)\n    at References.validate (C:\\Users\\Rishabh\\Desktop\\firefox\\taskcluster\\taskcluster\\libraries\\references\\src\\references.js:129:5)\n    at References.validate (C:\\Users\\Rishabh\\Desktop\\firefox\\taskcluster\\taskcluster\\libraries\\references\\src\\references.js:124:16)\n    at References.makeSerializable (C:\\Users\\Rishabh\\Desktop\\firefox\\taskcluster\\taskcluster\\libraries\\references\\src\\references.js:148:10)\n    at References.generateReferences (C:\\Users\\Rishabh\\Desktop\\firefox\\taskcluster\\taskcluster\\libraries\\references\\src\\references.js:241:59)\n
 at setup (C:\\Users\\Rishabh\\Desktop\\firefox\\taskcluster\\taskcluster\\services\\treeherder\\src\\main.js:65:8)\n    at Promise (C:\\Users\\Rishabh\\Desktop\\firefox\\taskcluster\\taskcluster\\libraries\\loader\\src\\index.js:149:33)\n    at new Promise (<anonymous>)\n    at loaded.(anonymous function).Promise.all.then.deps (C:\\Users\\Rishabh\\Desktop\\firefox\\taskcluster\\taskcluster\\libraries\\loader\\src\\index.js:147:18)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)\n',
  stderr: '' }
error Command failed with exit code 1.
```

I am not sure if I get this because of ```go mod tidy``` because I _couldn't_  successfully run `yarn generate` even when I hadn't made any changes.

**Comment by djmitche** [comment]
Ah, in general Taskcluster services don't run correctly directly on Windows.  You'd need to run `yarn generate` on a Linux-style system, such as in WSL.  If you'd prefer, I can run `yarn generate` and push the result to this PR.

**Comment by rbrishabh** [comment]
> 
> Ah, in general Taskcluster services don't run correctly directly on Windows. You'd need to run `yarn generate` on a Linux-style system, such as in WSL. 

Even after running on WSL, I get this error: 
```

Error: /mnt/c/users/rishabh/desktop/firefox/taskcluster/taskcluster/node_modules/libxmljs/build/Release/xmljs.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at bindings (/mnt/c/users/rishabh/desktop/firefox/taskcluster/taskcluster/node_modules/bindings/bindings.js:84:48)
    at Object.<anonymous> (/mnt/c/users/rishabh/desktop/firefox/taskcluster/taskcluster/node_modules/libxmljs/lib/bindings.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/c/users/rishabh/desktop/firefox/taskcluster/taskcluster/node_modules/libxmljs/index.js:4:16)

    at ChildProcess.exithandler (child_process.js:294:12)





  killed: false,
  code: 1,
  signal: null,
  cmd: 'node src/main generateReferences',
  stdout: '',
  stderr:
   '/mnt/c/users/rishabh/desktop/firefox/taskcluster/taskcluster/node_modules/bindings/bindings.js:91\n        throw e\n        ^\n\nError: /mnt/c/users/rishabh/desktop/firefox/taskcluster/taskcluster/node_modules/libxmljs/build/Release/xmljs.node: invalid ELF header\n    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)\n    at
Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at bindings (/mnt/c/users/rishabh/desktop/firefox/taskcluster/taskcluster/node_modules/bindings/bindings.js:84:48)\n    at Object.<anonymous> (/mnt/c/users/rishabh/desktop/firefox/taskcluster/taskcluster/node_modules/libxmljs/lib/bindings.js:1:37)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n
   at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (/mnt/c/users/rishabh/desktop/firefox/taskcluster/taskcluster/node_modules/libxmljs/index.js:4:16)\n' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```



> If you'd prefer, I can run `yarn generate` and push the result to this PR.

Yes please, that would be great!

**Comment by djmitche** [comment]
It looks like `node_modules/libxmljs/build/Release/xmljs.node` was compiled for windows, probably before using WSL.  Removing the entire `node_modules` directory and re-running `yarn install` under WSL should fix that.

**Comment by rbrishabh** [comment]
Alright thanks!

This time the tests actually completed.



However, scrolling up the logs, some of the client-shell Generate commands are shown with this icon :



Although, in the end, they all had tick mark icons.

> 
> 
> Did you run `yarn generate` locally and check in the changes it makes? The logs look like the result of running `go mod tidy`.

It makes more than 5000 changes in files. Which change am I looking for in particular?

**Comment by djmitche** [comment]
It shouldn't -- it should only make the changes in the last commit I pushed.  Can you paste the first bit of `git diff` output?

**Comment by djmitche** [comment]
..but I see that even my push failed as `go mod tidy` wanted to make other changes.  I've tried running `go mod tidy` again and pushing again.  Let's see what happens.  We might need to run `go mod tidy` a few times in a loop in `yarn generate`!

**Comment by rbrishabh** [comment]
> 
> 
>We might need to run `go mod tidy` a few times in a loop in `yarn generate`!

Okay. How many times would that be? Until the tests start passing?

**Comment by djmitche** [comment]
Hm, well, I've run it several times now and it's still giving a different result in the runs on this PR, so I don't think re-running it helps after all.

Part of the issue may be that I don't have `bzr` installed (it's a version control tool like git), and a test dependency of a dependency of a dependency of client-shell requires `launchpad.net/gocheck` which is a bzr repository.  But `bzr` *is* installed in the CI environment, so it succeeds there.  I definitely don't want to make TC developers install bzr, though.

I'll push a fix that uses the `replace` directive in `go.mod` to redirect to the newer `go-check` repository.  Let's see if that push passes!

**Comment by rbrishabh** [comment]
I guess it doesn't as well ~

**Comment by djmitche** [comment]
Ugh, indeed.  Frustrating!

Maybe we should just drop this idea until `go mod` is a little more mature and well-behaved.  What do you think?

**Comment by rbrishabh** [comment]
Yup, that would be ideal for now.
I'm closing this PR then, but I will be around!

If I can be of service anywhere, I would love to help. Just @ me. =)

**Comment by djmitche** [comment]
@rbrishabh here are a few ideas:
 * https://bugzilla.mozilla.org/show_bug.cgi?id=1437193
 * https://bugzilla.mozilla.org/show_bug.cgi?id=1519730
 * https://bugzilla.mozilla.org/show_bug.cgi?id=1526503
 * https://bugzilla.mozilla.org/show_bug.cgi?id=1551846
 * https://bugzilla.mozilla.org/show_bug.cgi?id=1563373

do any of those strike your fancy?

**Pull request closed without merging**
