### PR TITLE
Serve HTML documents as attachments

### PR DESCRIPTION
**Pull request by djmitche**
Bugzilla Bug: [1442024](https://bugzilla.mozilla.org/show_bug.cgi?id=1442024)

### CODE REVIEW

**Comment by djmitche** [comment]
@ajvb the change to ui/docs/reference/platform/object/simple-downloads.mdx is probably all you need to look at here, as the rest just implements it.

I think the big question I have is: is just `text/html` enough?  Do we need to consider image types? stylesheets? other things?

**Review by petemoore — APPROVED** [review]
This looks like a welcome security improvement, but I'll let @ajvb give a more thorough interpretation. Nice work!

**Review by ajvb — APPROVED** [review]
From a security perspective, this lgtm.

**Comment by djmitche** [comment]
Thanks all!  I'll fix the lint and merge.

**Pull request merged**
