### PR TITLE
feat(github): Github badges: more states and colors

### LINKED ISSUE #5271: Github badges are not very distinguishable between error/success
There's no color difference between the badges.

While the cat is cute I don't think it's very helpful to distinguish different states. IMO badges should be changed to match the github ones (green/red/yellow) to be recognizable.

### PR DESCRIPTION
**Pull request by lotas**
Fixes #5271

Added more states that might appear in github checks' conclusions.

Redesigned badges:

success
failure
pending
error
neutral
newrepo
skipped
stale
timed_out
action_required
cancelled

### CODE REVIEW

**Review by matt-boris — DISMISSED** [review]

**Review by matt-boris — APPROVED** [review]

**Comment by Eijebong** [comment]
I find the text pretty hard to read on some of those, especially the `action required` one.

**Comment by lotas** [comment]
improved badges once again. Aligned all sizes and fixed text contrast

**Comment by Eijebong** [comment]
Yup, way better :+1:

**Review by matt-boris — APPROVED** [review]

**Review by matt-boris — APPROVED** [review]

**Comment by matt-boris** [comment]
`client-rust` ran successfully on a rerun https://community-tc.services.mozilla.com/tasks/WjaAc564R4SB0h51IAr8KQ.

**Pull request merged**
