### PR TITLE
replaced graceful with gorilla mux in signin.go

### LINKED ISSUE #4594: Stop using gopkg.in/tylerb/graceful.v1
See https://bugzilla.mozilla.org/show_bug.cgi?id=1581546 for background.

### PR DESCRIPTION
**Pull request by marti1125**
Bugzilla Bug: [1581546](https://bugzilla.mozilla.org/show_bug.cgi?id=1581546)

Github Bug/Issue: Fixes #4594

### CODE REVIEW

**Review by djmitche — COMMENTED** [review]
Pretty cool!  Can you remove the commented-out code, so the diff in the PR is more readable?

I'm a little unclear how this works, though -- in the original implementation, once the handleFunc is called, it calls `s.Stop()` which stops the server.  I don't see an equivalent stopping occurring in this implementation.

With that addressed, @petemoore is a good reviewer for golang code so I'll ask him to do the next round.

**Comment by djmitche** [comment]
Ah, and the test failures are due to a missing `go mod tidy` in the root of the repo, I think.

**Comment by marti1125** [comment]
sure I removed all comments
About s.Stop() I added this
```
// Stop server
ctx, cancel := context.WithTimeout(context.Background(), 50*time.Millisecond)

defer cancel()

if err := srv.Shutdown(ctx); err != nil {
return fmt.Errorf("failed to shutdown localhost server, error: %s", err)
}
```

**Comment by djmitche** [comment]
Does that shut down the server immediately?

Overall, it's not working for me:
```
rubin ~ $ TASKCLUSTER_ROOT_URL=https://firefox-ci-tc.services.mozilla.com ./tmp/tc signin
INFO Starting                                     
INFO Listening for a callback on: http://localhost 
INFO Opening URL: https://firefox-ci-tc.services.mozilla.com/auth/clients/create?scope=%2A&name=cli-cF8M-D&expires=1d&callback_url=http%3A%2F%2Flocalhost&description=Temporary+client+for+use+on+the+command+line 
Error: failed to start localhost server, error: listen tcp: address http://localhost:0: too many colons in address
```

**Comment by marti1125** [comment]
Hi @djmitche How to I can test in local ? 
I fixed if you don't set port it won't append to callbackURL
Error: failed to start localhost server, error: listen tcp: address http://localhost:0: too many colons in address

**Comment by djmitche** [comment]
Here's what I did:
```
$ cd clients/client-shell
$ go build -o taskcluster .
$ TASKCLUSTER_ROOT_URL=https://community-tc.services.mozilla.com ./taskcluster signin
```

You should be able to sign in to community-tc with GitHub and complete the process.

**Comment by djmitche** [comment]
How's this going?

**Pull request closed without merging**
