### PR TITLE
Add worker-runner to the release process

### PR DESCRIPTION
**Pull request by walac**
* `yarn generate` runs `util/update-readme.go`
*  `yarn release` updates `worker-runner` version
* `yarn release:publish` add `worker-runner` binaries to the release artifacts

Each commit is self contended to make reviewing easier.

### CODE REVIEW

**Comment by walac** [comment]
@djmitche any idea on how to test the release related code?

**Comment by djmitche** [comment]
There are some steps in the dev-docs about doing a staging release that might help

**Comment by djmitche** [comment]
Also this is awesome!  Will review soon..

**Comment by djmitche** [comment]
(I don't know why netlify failed but it's unrelated)

**Pull request merged**
