### PR TITLE
Update to Karma 6.1.0

### LINKED ISSUE #4256: Upgrade to Karma 6
[Karma 6.0.0](https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#600-2021-01-13) has some dependency updates to fix CVEs, and also has some breaking changes that prevent a smooth upgrade. See PR #4253 for the failing tests.

Known issues:

* [karma-webpack](https://github.com/ryanclark/karma-webpack) uses dependency injection for ``customFileHandlers``, which is not supported in Karma 6.0.0 (but is in 6.0.1)

### PR DESCRIPTION
**Pull request by jwhitlock**
Github Bug/Issue: Fixes #4256

Previous dependabot PRs:
* PR #4352 - karma-webpack update (which may require an update to webpack 5)
* PR #4253 - karma update

### CODE REVIEW

**Comment by djmitche** [comment]
well that's disappointing :(

bad karma?

**Comment by jwhitlock** [comment]
[Karma 6.0.1](https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#601-2021-01-20) added ``customFileHandlers``, which means the previous version, ``karma-webpack`` 4.0.2, will work with it. However, ``karma-webpack 5.0.0 includes an update to webpack 5, which is blocked by the neutrino update (PR #4001).

I'm going to change this to a Karma update, and add ``karma-webpack`` to the webpack 5 bug.

**Comment by jwhitlock** [comment]
The failing test is CodeQL, which added some new rules recently and is identifying code not in this PR.

**Review by djmitche — APPROVED** [review]
Looks good!

**Pull request merged**
