### PR TITLE
rust client: document where  should appear instead of panicing

### LINKED ISSUE #4269: Thread task.projectId through UI
* add projectId to web-server's Task entity
* add projectId to the default task-creator task, with a site-specific value
* show projectId in task inspector

### LINKED ISSUE #4296: Be more lenient about trailing slashes in client-rust's `path_prefix`
This currently panics if there are trailing slashes, and @imbstack pointed out that it'd be just as easy to simply strip those.

### PR DESCRIPTION
**Pull request by djmitche**
Github Bug/Issue: Fixes #4296

### CODE REVIEW

**Review by jwhitlock — APPROVED** [review]
Thanks @djmitche, I agree that we should get away from panics. I do wonder if we should validate the ``path_prefix`` somewhere. Maybe a ``PathPrefix`` class that wraps the string? Maybe in ``Client::new``? It looks like the internal code is the most frequent caller, so maybe it is OK. I'll defer to @imbstack, who raise the issue the first time.

Also, next time you touch the code, please replace ``Unkown`` with ``Unknown``

**Comment by djmitche** [comment]
I skipped validation because it's internal code, yes.  I wanted to avoid adding `Result` to the return type for the functions that check this, but now that I look they all already return `Result`.  So I'll just add an error message.

**Comment by djmitche** [comment]
(Except `.path_prefix`, which is part of the builder pattern.  I think the assert is OK there)

**Review by jwhitlock — APPROVED** [review]
Thanks, I'm more comfortable with this. Which means little from a beginner Rust developer...

**Comment by djmitche** [comment]
I think your intuition is good :)

**Pull request merged**
