### PR TITLE
[aws-provider] Disallow entries in worker-pool that are used by the provider.

### PR DESCRIPTION
**Pull request by tomprince**

### CODE REVIEW

**Comment by owlishDeveloper** [comment]
Can you please the config that revealed the bug?

**Comment by tomprince** [comment]
I discovered the bug by inspection, when working on #1737 (I don't recall if it was when seeing if it was implemented, or when adjusting the schema for it).

**Comment by owlishDeveloper** [comment]
@tomprince I added a test framework for schemas. (you'll find a sample test in `worker-manager/test/schema_validate_test.js`) Can you please add a test case for this change?

**Comment by tomprince** [comment]
> @tomprince I added a test framework for schemas. (you'll find a sample test in `worker-manager/test/schema_validate_test.js`) Can you please add a test case for this change?

It looks like it doesn't now about providers, so it will accept anything in `config`.

**Comment by owlishDeveloper** [comment]
This was already merged

**Pull request closed without merging**
