### PR TITLE
Add esm output to client-web

### PR DESCRIPTION
**Pull request by helfi92**
Relates to https://github.com/taskcluster/taskcluster/issues/285.

### CODE REVIEW

**Comment by helfi92** [comment]
`yarn build` successfully generates both bundles however the process doesn't seem to exit...

**Comment by helfi92** [comment]
@edmorley Any idea/thoughts about why the process hangs even though the bundles are successfully generated? https://github.com/taskcluster/taskcluster/blob/ae45db83fbcf5947d271b7674718dc8fd5932469/clients/client-web/.neutrinorc.js#L44-L69

**Comment by edmorley** [comment]
`@neutrinojs/fork` is removed in Neutrino 9 -- I would update to Neutrino 9 first and then use the new approach mentioned here:
https://master.neutrinojs.org/migration-guide/#neutrino-v8-to-v9

**Comment by edmorley** [comment]
Also Neutrino 8 uses webpack 3, which doesn't support tree shaking.

**Comment by helfi92** [comment]
@edmorley What's stopping us from moving to neutrino v9 was https://github.com/neutrinojs/neutrino/issues/1251 which was recently resolved :) Any idea about when this can be published?

**Comment by edmorley** [comment]
Ah I forgot that issue was from this package. A new release will be out soon (likely once merged), however the issue you link can be worked around on the caller's side too, via a manual `neutrino.config.externals.clear()` call (or similar) during testing only.

**Comment by djmitche** [comment]
Does #445 supersede this?

**Comment by helfi92** [comment]
Indeed.

**Pull request closed without merging**
