### PR TITLE
Renaming .md to .mdx

### PR DESCRIPTION
**Pull request by iFlameing**
Fixes: Bugzilla Bug: [1530790](https://bugzilla.mozilla.org/show_bug.cgi?id=1530790)

@djmitche can you review this?

### CODE REVIEW

**Comment by iFlameing** [comment]
@djmitche I think we should wait for @helfi92. Because right now no option solve this bug completely. what do you think?

**Comment by djmitche** [comment]
It's true, but it will correctly display README.md files :)

**Comment by djmitche** [comment]
Maybe we should do this work *after* we move the files from `services/*/docs` into `ui/docs` -- it will probably make a lot more sense at that point.  And the READMEs will not move (although some of their content might be moved out to documentation files).

**Comment by helfi92** [comment]
> Maybe we should do this work after we move the files from services/*/docs into ui/docs -- it will probably make a lot more sense at that point. And the READMEs will not move (although some of their content might be moved out to documentation files).

Agreed. I think that's a good plan!

**Comment by djmitche** [comment]
Closing to continue after the move..

**Pull request closed without merging**
