### PR TITLE
Upgrade node-pg to 8.x without changing functionality

### LINKED ISSUE #3588: Allow un-verified SSL connections again
..but document how to verify them.

node-pg 8.x now defaults to expecting "authorized" SSL certs -- hostname match, etc.  When using a raw Cloud SQL IP, that doesn't happen.

So, let's give users options:
 - use an unauthorized SSL connection (which has been the default until now)
 - supply certificates, etc. (which has always been possible)

### PR DESCRIPTION
**Pull request by djmitche**
As a bonus, database URLs can now be specified in the configuration with `ssl=authorized`, in which case Taskcluster will validate the Postgres server's SSL/TLS certificate against trusted root CAs.  It is unusual for databases to be deployed with such certificates.  See [the documentation](https://docs.taskcluster.net/docs/manual/deploying/database#configuration) for details.

I seriously doubt anyone will use this option, but I did verify that running `yarn dev:db:upgrade` with this value in the DB URL caused the expected 
```
code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
```

so I think it works :)

Github Bug/Issue: Fixes #3588

### CODE REVIEW

**Review by petemoore — CHANGES_REQUESTED** [review]
@djmitche It looks like this caused a postgres related test failure:

```
$ node infrastructure/tooling/src/main.js test:meta
[22:27:49] Every DB version has a test script: running
[22:27:49] Dependencies are used and installed: running
[22:27:49] Docs headings match expectations: running
[22:27:49] Services are not using node-pg: running
[22:27:49] Proper spelling and capitalization of Taskcluster: running
[22:27:49] Test scripts do not use `test.only(..)`: running
[22:27:49] Node versions match: running
[22:27:49] Workspace package.json files do not have forbidden fields: running
[22:27:49] Every DB version has a test script: finished
[22:27:49] Docs headings match expectations: finished
[22:27:49] Node versions match: finished
[22:27:49] Workspace package.json files do not have forbidden fields: finished
[22:27:49] Test scripts do not use `test.only(..)`: finished
[22:27:49] Services are not using node-pg: finished
[22:27:50] Dependencies are used and installed: setting up
[22:27:50] Dependencies are used and installed: listing files
[22:27:50] Dependencies are used and installed: parsing requires
[22:27:50] Proper spelling and capitalization of Taskcluster: finished
[22:27:51] Dependencies are used and installed: failed
[22:27:51] Dependencies are used and installed: fail: Error: Dependency 'pg-connection-string' in libraries/postgres/src/Database.js is missing! It must be included in package.json dependencies!
Error: Dependency 'pg-connection-string' in libraries/postgres/src/Database.js is missing! It must be included in package.json dependencies! (while executing task Dependencies are used and installed)
    at CallExpression (/taskcluster/infrastructure/tooling/src/meta/checks/depcheck.js:77:17)
    at c (/taskcluster/node_modules/acorn-walk/dist/walk.js:30:20)
    at Object.skipThrough (/taskcluster/node_modules/acorn-walk/dist/walk.js:186:39)
    at c (/taskcluster/node_modules/acorn-walk/dist/walk.js:29:24)
    at Object.base.VariableDeclarator (/taskcluster/node_modules/acorn-walk/dist/walk.js:285:22)
    at c (/taskcluster/node_modules/acorn-walk/dist/walk.js:29:24)
    at Object.base.VariableDeclaration (/taskcluster/node_modules/acorn-walk/dist/walk.js:280:7)
    at c (/taskcluster/node_modules/acorn-walk/dist/walk.js:29:24)
    at Object.skipThrough (/taskcluster/node_modules/acorn-walk/dist/walk.js:186:39)
    at c (/taskcluster/node_modules/acorn-walk/dist/walk.js:29:24)
error Command failed with exit code 1.
```

**Comment by djmitche** [comment]
Weird, I even have the `yarn add -W` command to add that dep in my command line history, but somehow it didn't make it into the commit!

**Comment by djmitche** [comment]
Oh, I should read the yarn messages more carefully:
```
warning "pg-connection-string" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies".
```

**Review by petemoore — APPROVED** [review]
Looks good, many thanks!

**Pull request merged**
