### PR TITLE
Bug 1525786 - generate tc-client-web

### PR DESCRIPTION
**Pull request by djmitche**
This moves generation into `yarn generate` (part of
taskcluster-builder).  Note that with this change the client no longer
has built-in documentation.  That documentation was incomplete anyway,
and I'd prefer that people refer to the documentation on the website.

Bugzilla Bug: [1525786](https://bugzilla.mozilla.org/show_bug.cgi?id=1525786)

### CODE REVIEW

**Comment by djmitche** [comment]
(rebased)

**Comment by djmitche** [comment]
Looks like yarn is down.  It was green before the rebase.  I'll close and reopen to trigger a new run.

**Comment by djmitche** [comment]
```
11:32:20 AM: warning There appears to be trouble with our server. Retrying...
11:32:23 AM: error https://registry.yarnpkg.com/@mozilla-frontend-infra/components/-/components-2.2.2.tgz: Integrity check failed for "@mozilla-frontend-infra/components" (computed integrity doesn't match our records, got "sha512-gRqo26GlY1g7geLRIoeFwf0Ge+14gpbwryKgvNcTy8IUgv2/uFDOWUgaeJ6AVQmxVk1eTIj6E/l9dA1vWkSfDg==")
```

I'll just push through that, since the taskcluster-client-web check was successful.

**Comment by helfi92** [comment]
Perhaps `yarn.lock` needs an update?

**Comment by djmitche** [comment]
I think it was just a server issue..

**Pull request merged**
