### PR TITLE
Document exchanges for worker-manager

### PR DESCRIPTION
**Pull request by djmitche**
Tested manually

image

### CODE REVIEW

**Review by matt-boris — APPROVED** [review]
LGTM, thank you! Just one note is your commit comes up as `Unverified`. Wonder what GitHub doesn't like about your signature..

Screen Shot 2022-04-01 at 11 35 26 AM

**Comment by Eijebong** [comment]
@matt-boris from https://github.com/djmitche 

> NOTE: if you see "Unverified" next to my commits, that's because they're signed with my [SSH key](https://github.com/djmitche.keys), and GitHub does not yet support SSH signatures.

**Review by petemoore — APPROVED** [review]
Awesome, thanks!!

**Comment by djmitche** [comment]
(I have a pending support case open with GitHub for that..)

**Pull request merged**
