### PR TITLE
Always allow collapsing the drawer

### PR DESCRIPTION
**Pull request by iFlameing**
Regarding issue #225 

@helfi92 can you make some comment on this. The only problem is that when I am making `drawerOpen true`  I am able to show the drawer in desktop mode but I am not able to remove it when I am clicking on any sidebar list. can you take a look or suggest me anything after looking this?

### CODE REVIEW

**Comment by iFlameing** [comment]
@helfi92 thanks, I think it is ready for review. can you review this? :)

**Comment by iFlameing** [comment]
@helfi92 I modify my code as you said and saw that previously for Documentation also we have a temporary variant drawer. But with these changes, we have a permanent drawer as it is important for a newcomer. But there is a problem in mobile view which I didn't like i.e( when we are clicking on the DocsSidebarList, drawer is still open and we have to click on the backdrop to close it.) What do you think and also what should I do now after these changes?

**Comment by helfi92** [comment]
You can try to figure it out. I'm also ok merging after you add the requested changes then we could the issue you pointed out in a different PR.

**Comment by iFlameing** [comment]
@helfi92 I pushed the commit which is required. you can merge this now :) thanks for the help.

**Pull request merged**
