### PR TITLE
Slashes not allowed in index paths documentation addition to  api.js and index/README.mdx

### LINKED ISSUE #3721: Routes containing slashes do not get indexed, with no visible error
Thanks to @ricky26 for spotting this.  

https://community-tc.services.mozilla.com/tasks/c4FFtHALTq6MqZqZregE1Q
```
{
  "provisionerId": "built-in",
  "workerType": "succeed",
  "schedulerId": "taskcluster-ui",
  "taskGroupId": "c4FFtHALTq6MqZqZregE1Q",
  "dependencies": [],
  "requires": "all-completed",
  "routes": [
    "index.project.taskcluster.foo/bar/slash"
  ],
  "priority": "lowest",
  "retries": 0,
  "created": "2020-10-21T15:52:53.138Z",
  "deadline": "2020-10-22T03:52:53.138Z",
  "expires": "2020-10-28T15:52:53.138Z",
  "scopes": [],
  "payload": {},
  "metadata": {
    "name": "Testy",
    "owner": "unkown@localhost.local",
    "source": "http://foobar.com",
    "description": "jonas damn you <-- :heart:"
  },
  "tags": {},
  "extra": {}
}
```
this task succeeded, but no index entry appeared.  I don't see any logging (aside from db-pool-counts) from index at this time.  Modifying the task to change `/` to `.` in the route succeeds.

Nothing in the [AMQP Spec](https://www.rabbitmq.com/resources/specs/amqp-xml-doc0-9-1.pdf) disallows `/`, so I think this is an issue in the index, and I'm not sure how best to make the error obvious to users.

### PR DESCRIPTION
**Pull request by SushantAA**
Github Bug/Issue: Fixes #3721 
I have not done yarn generate. ( there is some problem with OS: ubuntu installation. I am trying to set up the environment from the past 3 days; hoping it to resolve soon)

### CODE REVIEW

**Review by djmitche — APPROVED** [review]
Looks good!  I ran `yarn generate` and added a silent changelog (`yarn changelog --silent`).  Once the tests pass, we can get this merged!

**Comment by djmitche** [comment]
(I rebased onto master, as that fixes the failures in the previous version)

**Comment by SushantAA** [comment]
It's done or I have to do it in the latest version?

**Comment by djmitche** [comment]
It's done -- I was just waiting to see that the checks passed.  Thanks!

We can try to help get your environment set up, and then find a more sophisticated issue for you to work on..

**Comment by SushantAA** [comment]
I would like to work on more issues. 
I am trying to set the environment in windows currently and in ubuntu also.

**Pull request merged**
