### PR TITLE
[UI] Make workers view mobile friendly

### PR DESCRIPTION
**Pull request by JiwoonKim**
**Closes Issue** #1585
breadcrumbs and dropdown components should both sit on their own lines
when the width of the screen is smaller

**Changes Applied**
added flex-wrap style to component

**Results**
- when width is smaller
small

### CODE REVIEW

**Comment by JiwoonKim** [comment]
@djmitche 
I accidentally pushed other commits onto this branch and opened a pull request #1627 based on that. Closed it soon after I realized the wrong commits were pushed and rebased the branch (after deleting it and then, recreating it...) but wasn't sure how to make the changes apply to the previous pull request at #1627 ... so I opened this new pull request instead. 

I hope this doesn't create any issues. This was my first time rebasing my code and I wasn't sure how to force-pull request.

**Comment by djmitche** [comment]
It's no problem.  There are ways to do it, but what you did is easier and just as effective :)

**Comment by JiwoonKim** [comment]
> @JiwoonKim if you rebase your changes on the latest master, that will fix these errors from the bot.

Thanks for the feedback!

**Comment by helfi92** [comment]
Very nice commit message as well!

**Pull request merged**
