### PR TITLE
Issue #5081: Avoid methods and functions that rely on go:uintptrescapes pragma

### LINKED ISSUE #5081: generic-worker stuck deleting a user profile
**Describe the bug**
A generic-worker hung, trying to delete a user profile.

Last line of log:

```
122022/01/24 18:17:59Z Making system call DeleteProfileW with args: [C0004B6000 0 0]
```

A reboot was issued, and then logs continued:

```
2022/01/25 09:58:22Z Making system call GetProfilesDirectoryW with args: [C000139380 C00037A248]
```

Each syscall is logged before being issued, and then the results of the syscall are logged. Since the log message that the syscall will be issued is shown, and the log message of the result did not appear, we can see the syscall hung.

Nothing in the UI to suggest there was an issue (such as a dialogue window reporting an error).

The code that didn't complete is https://github.com/taskcluster/taskcluster/blob/v44.2.2/workers/generic-worker/win32/win32_windows.go#L808-L812

Under the hood this calls https://github.com/golang/go/blob/go1.16.7/src/syscall/dll_windows.go#L335-L340

**Expected behavior**
We should probably have a timeout. And if cleanup of old users fails, that probably shouldn't be a critical failure and we should purge old users on a best-effort basis.

**Taskcluster version**
44.2.2

**Platform (please complete the following information):**

 - OS: Windows (unknown version)

**Additional context**

* Reported by @Eijebong for taskcluster deployment https://divvun-tc.thetc.se
* @petemoore has full logs, if needed

### PR DESCRIPTION
**Pull request by petemoore**
Github Bug/Issue: Fixes #5081

This is a more general version of the fix that was applied in #5090 but applies to _all_ custom syscalls that generic-worker makes on Windows.

### CODE REVIEW

**Comment by jwhitlock** [comment]
@petemoore I can do a rubber-stamp review, but I don't have the go knowledge, generic-worker experience, or the Windows development environment to test these changes.

**Review by lotas — APPROVED** [review]

**Comment by Eijebong** [comment]
Welp, deadlocks are back (with an old version of the worker) so it was not related to the environment changes. Going to switch to workers from this branch see if they appear

**Comment by Eijebong** [comment]
This PR doesn't fix it.

```
2022/03/21 11:51:38Z Granted S-1-1-0 full control of interactive windows station and desktop
2022/03/21 11:51:38Z Granting task_164786334012988 control of C:\Users\task_164786334012988
2022/03/21 11:51:38Z Running command: icacls 'C:\Users\task_164786334012988' /grant:r 'task_164786334012988:(OI)(CI)F'
2022/03/21 11:51:38Z Creating Windows user task_164786349732985...
2022/03/21 11:51:38Z Running command: net user task_164786349732985 pWd0_AqPPic2ClELvukLY20zvif6p /add /expires:never /passwordchg:no /y
2022/03/21 11:51:39Z Created new OS user!
2022/03/21 11:51:39Z Running command: wmic useraccount where name=\'task_164786349732985\' set passwordexpires=false
2022/03/21 11:51:40Z Running command: net localgroup 'Remote Desktop Users' /add task_164786349732985
2022/03/21 11:51:43Z Creating folder C:\Users\task_164786349732985\AppData\Roaming
2022/03/21 11:51:43Z Creating folder C:\Users\task_164786349732985\AppData\Local
2022/03/21 11:51:43Z The parameter is incorrect.
2022/03/21 11:51:43Z WARNING: Not able to redirect Local App Data folder to C:\Users\task_164786349732985\AppData\Local - IGNORING!
2022/03/21 11:51:43Z Saving file next-task-user.json (absolute path: c:\generic-worker\next-task-user.json)
2022/03/21 11:51:44Z Running command: icacls 'next-task-user.json' /grant:r 'Administrators:(GA)' /inheritance:r
2022/03/21 11:51:44Z Created dir: C:\Users\task_164786334012988\generic-worker
2022/03/21 11:51:44Z Trying to remove directory 'C:\Users\task_164786318051975' via os.RemoveAll(path) call...
2022/03/21 11:51:54Z Looking for existing task users to delete...
2022/03/21 11:51:54Z Running command: wmic useraccount get name
2022/03/21 11:51:55Z Attempting to remove user task_164786318051975...
```

```
(dlv) goroutines -t
  Goroutine 1 - User: c:/users/task_164389485825450/go1.17.6/go/src/runtime/syscall_windows.go:483 syscall.Syscall (0x8d0c74) (thread 5560) [sleep 457740h13m51.5895019s]
         0  0x00007ffd1a1adee4 in ???
             at ?:-1
         1  0x00000000008d21a0 in runtime.systemstack_switch
             at c:/users/task_164389485825450/go1.17.6/go/src/runtime/asm_amd64.s:350
         2  0x000000000087430c in runtime.cgocall
             at c:/users/task_164389485825450/go1.17.6/go/src/runtime/cgocall.go:166
         3  0x00000000008d0c74 in syscall.Syscall
             at c:/users/task_164389485825450/go1.17.6/go/src/runtime/syscall_windows.go:483
         4  0x00000000008d6cab in syscall.Syscall
             at :0
         5  0x0000000000b96de8 in github.com/taskcluster/taskcluster/v44/workers/generic-worker/win32.DeleteProfile
             at c:/users/task_164389485825450/taskcluster/workers/generic-worker/win32/win32_windows.go:902
         6  0x0000000000bf233e in github.com/taskcluster/taskcluster/v44/workers/generic-worker/runtime.DeleteUser
             at c:/users/task_164389485825450/taskcluster/workers/generic-worker/runtime/runtime_windows.go:62
         7  0x0000000000ccf9db in main.deleteExistingOSUsers
             at c:/users/task_164389485825450/taskcluster/workers/generic-worker/multiuser.go:192
         8  0x0000000000ccf5f3 in main.purgeOldTasks
             at c:/users/task_164389485825450/taskcluster/workers/generic-worker/multiuser.go:175
         9  0x0000000000cc5b85 in main.RotateTaskEnvironment
             at c:/users/task_164389485825450/taskcluster/workers/generic-worker/main.go:1171
        10  0x0000000000cbf005 in main.RunWorker
             at c:/users/task_164389485825450/taskcluster/workers/generic-worker/main.go:396
        (truncated)
  Goroutine 2 - User: c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367 runtime.gopark (0x8a95d6) [force gc (idle) 457739h55m42.871019s]
        0  0x00000000008a95d6 in runtime.gopark
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367
        1  0x00000000008a9471 in runtime.goparkunlock
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:372
        2  0x00000000008a9471 in runtime.forcegchelper
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:306
        3  0x00000000008d4521 in runtime.goexit
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/asm_amd64.s:1581
  Goroutine 3 - User: c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367 runtime.gopark (0x8a95d6) [GC sweep wait]
        0  0x00000000008a95d6 in runtime.gopark
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367
        1  0x0000000000893238 in runtime.goparkunlock
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:372
        2  0x0000000000893238 in runtime.bgsweep
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/mgcsweep.go:182
        3  0x00000000008d4521 in runtime.goexit
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/asm_amd64.s:1581
  Goroutine 4 - User: c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367 runtime.gopark (0x8a95d6) [GC scavenge wait]
        0  0x00000000008a95d6 in runtime.gopark
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367
        1  0x00000000008914a8 in runtime.goparkunlock
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:372
        2  0x00000000008914a8 in runtime.bgscavenge
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/mgcscavenge.go:314
        3  0x00000000008d4521 in runtime.goexit
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/asm_amd64.s:1581
  Goroutine 5 - User: c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367 runtime.gopark (0x8a95d6) [finalizer wait 457740h14m5.6945048s]
        0  0x00000000008a95d6 in runtime.gopark
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367
        1  0x0000000000888c73 in runtime.goparkunlock
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:372
        2  0x0000000000888c73 in runtime.runfinq
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/mfinal.go:177
        3  0x00000000008d4521 in runtime.goexit
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/asm_amd64.s:1581
  Goroutine 8 - User: c:/users/task_164389485825450/go1.17.6/go/src/runtime/sigqueue.go:169 os/signal.signal_recv (0x8cff78) (thread 4012)
        0  0x00007ffd1a1acdf4 in ???
            at ?:-1
        1  0x00000000008d21a0 in runtime.systemstack_switch
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/asm_amd64.s:350
        2  0x00000000008a2f5d in runtime.stdcall
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/os_windows.go:1068
        3  0x00000000008a3105 in runtime.stdcall2
            at :0
        4  0x00000000008a232f in runtime.semasleep
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/os_windows.go:818
        5  0x000000000087bb96 in runtime.notetsleep_internal
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/lock_sema.go:214
        6  0x000000000087becf in runtime.notetsleepg
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/lock_sema.go:296
        7  0x00000000008cff78 in os/signal.signal_recv
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/sigqueue.go:169
        8  0x0000000000bc2199 in os/signal.loop
            at c:/users/task_164389485825450/go1.17.6/go/src/os/signal/signal_unix.go:24
        9  0x00000000008d4521 in runtime.goexit
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/asm_amd64.s:1581
  Goroutine 14 - User: c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367 runtime.gopark (0x8a95d6) [GC worker (idle)]
        0  0x00000000008a95d6 in runtime.gopark
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367
        1  0x000000000088b725 in runtime.gcBgMarkWorker
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/mgc.go:1200
        2  0x00000000008d4521 in runtime.goexit
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/asm_amd64.s:1581
  Goroutine 15 - User: c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367 runtime.gopark (0x8a95d6) [GC worker (idle)]
        0  0x00000000008a95d6 in runtime.gopark
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367
        1  0x000000000088b725 in runtime.gcBgMarkWorker
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/mgc.go:1200
        2  0x00000000008d4521 in runtime.goexit
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/asm_amd64.s:1581
  Goroutine 19 - User: c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367 runtime.gopark (0x8a95d6) [GC worker (idle)]
        0  0x00000000008a95d6 in runtime.gopark
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367
        1  0x000000000088b725 in runtime.gcBgMarkWorker
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/mgc.go:1200
        2  0x00000000008d4521 in runtime.goexit
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/asm_amd64.s:1581
  Goroutine 20 - User: c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367 runtime.gopark (0x8a95d6) [GC worker (idle)]
        0  0x00000000008a95d6 in runtime.gopark
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367
        1  0x000000000088b725 in runtime.gcBgMarkWorker
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/mgc.go:1200
        2  0x00000000008d4521 in runtime.goexit
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/asm_amd64.s:1581
  Goroutine 34 - User: c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367 runtime.gopark (0x8a95d6) [GC worker (idle) 457739h55m43.0436113s]
        0  0x00000000008a95d6 in runtime.gopark
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367
        1  0x000000000088b725 in runtime.gcBgMarkWorker
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/mgc.go:1200
        2  0x00000000008d4521 in runtime.goexit
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/asm_amd64.s:1581
  Goroutine 35 - User: c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367 runtime.gopark (0x8a95d6) [GC worker (idle)]
        0  0x00000000008a95d6 in runtime.gopark
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367
        1  0x000000000088b725 in runtime.gcBgMarkWorker
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/mgc.go:1200
        2  0x00000000008d4521 in runtime.goexit
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/asm_amd64.s:1581
  Goroutine 36 - User: c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367 runtime.gopark (0x8a95d6) [GC worker (idle) 457739h55m43.067373s]
        0  0x00000000008a95d6 in runtime.gopark
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367
        1  0x000000000088b725 in runtime.gcBgMarkWorker
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/mgc.go:1200
        2  0x00000000008d4521 in runtime.goexit
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/asm_amd64.s:1581
  Goroutine 37 - User: c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367 runtime.gopark (0x8a95d6) [GC worker (idle) 457739h59m43.3930981s]
        0  0x00000000008a95d6 in runtime.gopark
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/proc.go:367
        1  0x000000000088b725 in runtime.gcBgMarkWorker
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/mgc.go:1200
        2  0x00000000008d4521 in runtime.goexit
            at c:/users/task_164389485825450/go1.17.6/go/src/runtime/asm_amd64.s:1581
[14 goroutines]
```

**Comment by petemoore** [comment]
It turned out that this wasn't the cause of the problem. So I'll close for now, as I don't think it helps. We can reopen later if we find it is useful for some other reason.

**Pull request closed without merging**
