### PR TITLE
Use a distinct port for internalGETPort in tests, too

### LINKED ISSUE #2783: generic-worker tests are connecting to parent livelog, crashing it
https://community-tc.services.mozilla.com/tasks/ayBq3Tp8SiawxTzH6psUBA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FayBq3Tp8SiawxTzH6psUBA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log
```
2020/05/07 21:30:57Z Creating task feature Mounts/Caches...
2020/05/07 21:30:57Z Creating task feature Supersede...
2020/05/07 21:30:57Z Starting task feature Live Log...
2020/05/07 21:30:57Z WARNING: Livelog failure: error 'exit status 1' and livelog output:
2020/05/07 21:30:57 input server listening... 
2020/05/07 21:30:57 listen tcp :60022: bind: address already in use
2020/05/07 21:30:58Z Starting task feature OS Groups...
[taskcluster 2020-05-07T21:30:59.394Z] Uploading redirect artifact public/logs/live.log to URL https://community-tc.services.mozilla.com/api/queue/v1/task/ayBq3Tp8SiawxTzH6psUBA/runs/0/artifacts/public/logs/live_backing.log with mime type "text/plain; charset=utf-8" and expiry 2021-05-08T21:29:33.022Z
[taskcluster:error] exit status 141
```

141 is from EPIPE, I think.

### PR DESCRIPTION
**Pull request by djmitche**
Fixes #2783 (hopefully)

### CODE REVIEW

**Comment by djmitche** [comment]
woo!

**Comment by petemoore** [comment]
@djmitche Thanks for this. I'm not sure what caused the tests to start failing, as they were passing in https://community-tc.services.mozilla.com/tasks/M8yBcUmtT-ymFmYWJiZEnw which was for commit 8aa892357d5aa5fdf657ff8919266db15922cc2b on master which landed when #2736 was merged. Do you know why the PR branch passed, and the merge commit on master passed, but things started failing later?

**Comment by petemoore** [comment]
> @djmitche Thanks for this. I'm not sure what caused the tests to start failing, as they were passing in [task M8yBcUmtT-ymFmYWJiZEnw](https://community-tc.services.mozilla.com/tasks/M8yBcUmtT-ymFmYWJiZEnw) which was for commit [8aa8923](https://github.com/taskcluster/taskcluster/commit/8aa892357d5aa5fdf657ff8919266db15922cc2b) on master which landed when #2736 was merged. Do you know why the PR branch passed, and the merge commit on master passed, but things started failing later?

Ah I see 16.5.6 that [task M8yBcUmtT-ymFmYWJiZEnw](https://community-tc.services.mozilla.com/tasks/M8yBcUmtT-ymFmYWJiZEnw) ran against [generic-worker 16.5.6](https://community-tc.services.mozilla.com/tasks/M8yBcUmtT-ymFmYWJiZEnw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FM8yBcUmtT-ymFmYWJiZEnw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L15) whereas e.g. [task LbrYwsf_SPqJMbqJWNxs6g](https://community-tc.services.mozilla.com/tasks/LbrYwsf_SPqJMbqJWNxs6g) runs against [generic-worker 29.2.0](https://community-tc.services.mozilla.com/tasks/LbrYwsf_SPqJMbqJWNxs6g/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FLbrYwsf_SPqJMbqJWNxs6g%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L15).

Did the websocktunnel/livelog integration use a different hardcoded port in generic-worker 16.5.6, or something like that?

**Comment by djmitche** [comment]
The old livelog didn't correctly report errors, so until golangci-lint caught that problem when we merged it to the monorepo, this never caused any issues.  I would guess that your first fix to this addressed the issue in the case where the outer worker was using an old livelog (which didn't report errors correctly).  But on upgrading the outer worker to 29.x, that outer livelog started reporting errors and terminating the task abruptly when the inner worker contacted the outer livelog.

Anyway, I like you spent some time trying to figure out the history of this but, but the above conjecture is about as far as I've gotten -- this seems to fix the issue, at any rate.

Once we [get rid of stateless DNS in g-w](https://bugzilla.mozilla.org/show_bug.cgi?id=1636321) the worker won't need to expose any ports for livelog.  At that point, all port numbers are invisible to the user and we can let the kernel allocate them, by specifying port 0 and reading the port after the socket is bound.  Then all of this config madness will disappear :)

**Comment by djmitche** [comment]
@petemoore if you are OK with this please merge it!

**Pull request merged**
