### PR TITLE
Document that paths are absolute in docker-worker artifacts

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by petemoore** [comment]
@djmitche Have you tested with a relative path, to be sure they don't work?

**Comment by djmitche** [comment]
No, I'm not sure what it would be relative to. I added this because in chat I was pretty sure the paths were absolute but didn't find a statement here in the schema.  It is documented as a full path in /docs/manual/using/artifacts.

**Comment by djmitche** [comment]
I don't know what's up with the Python failures!

```
AttributeError: module 'virtualenv.activation.python' has no attribute 'PestythonActivator'
```

I don't see anything related in the diff, and

```
lamport ~/p/taskcluster2 [d-w-path-absolute] $ git grep Pestython
lamport ~/p/taskcluster2 [d-w-path-absolute] $ git grep Pest
lamport ~/p/taskcluster2 [d-w-path-absolute] $ git grep -i Pestython
```

**Comment by djmitche** [comment]
#3046.

**Pull request merged**
