### PR TITLE
Drop support for legacy assume:worker-id:.. queue scopes

### LINKED ISSUE #4586: Deprecate `assume:worker-id:..` scopes
This scope pattern is already deprecated in almost every API endpoint *except* `queue.createArtifact`.

```
  scopes: { AnyOf: [
    'queue:create-artifact:<taskId>/<runId>',
    { AllOf: [
      'queue:create-artifact:<name>',
      'assume:worker-id:<workerGroup>/<workerId>',                                                                                
    ] },
  ] },
```

I suspect it's unused there, as well -- that all usage by workers uses the first alternative in the AnyOf.  If so, let's consider it to have been completely deprecated and remove support.  Otherwise, let's fix this usage and declare a future date after which support will be removed.

* https://github.com/taskcluster/taskcluster-rfcs/pull/71
* https://bugzilla.mozilla.org/show_bug.cgi?id=1374978

### PR DESCRIPTION
**Pull request by djmitche**
Github Bug/Issue: Fixes #4586

### CODE REVIEW

**Review by imbstack — APPROVED** [review]

**Comment by imbstack** [comment]
Although tests are failing

**Comment by djmitche** [comment]
I'll have a look-see, thanks!

**Comment by djmitche** [comment]
I hadn't put the right creds in to run `artifact_test.js` locally, so I had forgotten to update the scopes it uses.  I force-pushed with only changes to that file, so I'll merge if green.

**Comment by djmitche** [comment]
The failures here are all due to a yarn outage, it looks like.

**Pull request merged**
