### PR TITLE
Add upgrade documentation

### PR DESCRIPTION
**Pull request by MasterWayZ**
This is just off the top of my head, improvements are likely needed and are welcome.

### CODE REVIEW

**Review by lotas — APPROVED** [review]
Thanks!

**Comment by lotas** [comment]
@MasterWayZ can you please rebase this and possible drop `yarn.lock`, since there are no changes to the packages? 
Thank you

**Comment by MasterWayZ** [comment]
@lotas after some git wizarding (I know hg better than git at this point haha), I hope it has worked out well.

**Comment by lotas** [comment]
thanks @MasterWayZ 
tests are currently failing for Azure tests, and this is a known issue. I will merge it anyway, as this is a documentation fix

**Review by lotas — APPROVED** [review]

**Pull request merged**
