### PR TITLE
[UI] Date distance precision

### PR DESCRIPTION
**Pull request by helfi92**
Fixes https://github.com/taskcluster/taskcluster/issues/2005.

### CODE REVIEW

**Comment by SimonSapin** [comment]
I don’t know what parts of the UI use what part of the code, but https://community-tc.services.mozilla.com/tasks/IpzWeA6ZSgairHSwGk3s3Q uses "about" which looks like a call to `formatDistance` rather than `formatDistanceStrict`. Is this PR modifying the right call?

The cut-off at 120 minutes means that we could still have imprecise "about 2 hours" or "about 3 hours" etc. But I’m ok with declaring that any single task that takes that long is a bug anyway :)

**Comment by helfi92** [comment]
@SimonSapin I added the change to the offset time as well.

Screen Shot 2019-11-18 at 11 20 44 AM

**Comment by SimonSapin** [comment]
Looks good, thanks!

**Comment by djmitche** [comment]
It looks like this test [can fail](https://community-tc.services.mozilla.com/tasks/Wtr2HHYwQ9yp_9Fwdl6yiA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FWtr2HHYwQ9yp_9Fwdl6yiA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log).

**Comment by helfi92** [comment]
I pushed a hotfix yesterday to fix the test. Rebasing on master should do it.

**Pull request merged**
