### PR TITLE
add debug info to client::tests::test_simple_request_with_perm_creds

### PR DESCRIPTION
**Pull request by djmitche**
Github Bug/Issue: #5016

This just adds debug info.  Assuming I can make this fail on the PR, I shouldn't need to merge this.

### CODE REVIEW

**Comment by petemoore** [comment]
@djmitche do you want to try pushing some empty commits to trigger the intermittent failure, or do you want me to rubber stamp it and merge it (and potentially revert it later if it is too noisy)?

**Comment by djmitche** [comment]
close/reopen should trigger new runs.  I'll try to do a few of those.  If it still doesn't reproduce, then the `println!`s I added are probably adjusting some timing such that the error doesn't occur -- which suggests this is a race condition :(

**Comment by djmitche** [comment]
Well, this _is_ frustrating, isn't it.

**Comment by djmitche** [comment]
(btw I don't have perms to rerun or retrigger or edit-and-create)

**Comment by djmitche** [comment]
@petemoore let's merge this to main.  It's definitely not noisy.  And if it doesn't fail anymore, 🤷🏽 ?

**Review by petemoore — APPROVED** [review]

**Pull request merged**
