### PR TITLE
[UI] next/prev icon in light theme

### PR DESCRIPTION
**Pull request by aryamanpuri**
Reopened #1773

### CODE REVIEW

**Comment by helfi92** [comment]
@aryamanpuri Are you planning to open another pull-request?

**Comment by aryamanpuri** [comment]
@helfi92 yes I am going to make another one. 
I have a question  as the issue #1773 is closed , is it responsible for the failed checks.

**Comment by helfi92** [comment]
@aryamanpuri No, it's not responsible for the failed checks. You can see why the checks are failing by looking at the taskcluster-ui logs (click on the red "X" icon then taskcluster-ui then view the logs) https://community-tc.services.mozilla.com/tasks/OT1GvZ_rSrqP_tUlnAsSCg/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FOT1GvZ_rSrqP_tUlnAsSCg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

**Comment by helfi92** [comment]
> @helfi92 yes I am going to make another one.

👍

**Pull request closed without merging**
