### PR TITLE
Bug 1524187 - Internal Server Errors when calling queue.completeArtifact

### PR DESCRIPTION
**Pull request by jhford**
This changes 500 ISE into 400 BadInput errors

Bugzilla Bug: [1524187](https://bugzilla.mozilla.org/show_bug.cgi?id=1524187)

### CODE REVIEW

**Comment by jhford** [comment]
These two latest commits should also be deployed.  The first is status code check.  I suspect that the reason the metadata header isn't being set is that the request is failing.  The second commit is only a debugging commit which we should deploy in staging to see what's going on.

**Comment by djmitche** [comment]
I don't think we want to merge and deploy this as-is (removing label).

**Comment by djmitche** [comment]
rebased and the DEBUGGING commit removed..

**Comment by imbstack** [comment]
Conservation of Bugmentum

**Pull request merged**
