### PR TITLE
docker-worker: add a timer for task setup, defaulting to 10 minutes

### PR DESCRIPTION
**Pull request by jcristau**
Limit the amount of time we can spend setting up the docker container for the task.
    
Bugzilla Bug: [1824937](https://bugzilla.mozilla.org/show_bug.cgi?id=1824937)

### CODE REVIEW

**Comment by petemoore** [comment]
Thanks for looking into this Julien! Do you think it would be possible to add a unit test? Ideally it would be great if the unit test could use a shorter timeout (e.g. 10ms) so that the unit test runs quickly. I realise this is still in draft, but wanted to give early feedback... Many thanks!

**Comment by jcristau** [comment]
Thanks for the feedback Pete!  The lack of a test is the reason this is still in draft actually :)

**Comment by jcristau** [comment]
The approach here is all wrong, so I'm going to close this.

**Comment by lotas** [comment]
Hey @jcristau do you mind sharing more details? Did you find some other issue or have a better fix on your mind?
Thanks!

**Comment by jcristau** [comment]
My patch didn't actually kill/interrupt the blocking operations, so it didn't fix anything (even aside from the fact that it caused docker-worker to call abortRun twice, and crash on the second call).

I was basing my change on the maxRunTime handling, but that's a lot different because what it needs to interrupt is in a separate process which it can just kill, whereas the blocking operation here may be things like an in-process http download or an out-of-process docker pull operation.
It might be easier to make changes similar to #6133 to other blocking operations, e.g. adding a timeout to the dockerode instance that we use for pulls.

As an aside, I've noticed e.g. https://github.com/taskcluster/taskcluster/blob/2c07f52a5dc41aec21513d605400df26b07bc51b/workers/generic-worker/mounts.go#L817 doesn't seem to set a timeout, either (if I'm reading it correctly), so there may be similar issues lurking in g-w as well.

**Pull request closed without merging**
