### PR TITLE
Improve docs for run/task states

### PR DESCRIPTION
**Pull request by djmitche**
Task states are derived from run states. This updates the docs to reflect this, and to include a diagram of run states. It also cautions against relying on absence of edges in the task state diagram.

This came up at a community meeting last week (and in particular the "Warning"), where I promised to update the docs accordingly.

### CODE REVIEW

**Comment by djmitche** [comment]
Fixes #7286.

**Review by lotas — APPROVED** [review]
Thanks Dustin! Great additions. 

btw, what do you use to generate those SVGs?

**Comment by lotas** [comment]
Can you also please add a changelog file before we can merge this?

**Review by lotas — APPROVED** [review]
Thanks!

**Pull request merged**
