### PR TITLE
[UI] Show relative date in a tooltip

### LINKED ISSUE #970: [UI] Show relative date in a tooltip
STR:

1. Navigate to https://taskcluster-ui.herokuapp.com/tasks/index/gecko.v2.mozilla-beta.latest.firefox/linux64-opt
2. Hover on text below "Created"

Actual: Nothing appears
Expected: Show the actual date in a tooltip

Something similar to:

Screen Shot 2019-07-04 at 2 56 27 PM

but without the "(copy)" part.

### PR DESCRIPTION
**Pull request by ivanicharts**
Add relative date in a tooltip

Fixes #970

### CODE REVIEW

**Comment by ivanicharts** [comment]
My first approved open source PR ever. Thanks @helfi92 :)

**Comment by helfi92** [comment]
w00t! Let me know if there's another issue you're interested in tackling. Happy to help :-)

**Comment by ivanicharts** [comment]
@helfi92 sure, thank you.

**Comment by helfi92** [comment]
@ivanicharts Let me know if you're interested in https://github.com/taskcluster/taskcluster/issues/627. Comment directly on the issue if you are :)

**Pull request merged**
