### PR TITLE
Remove azure library

### PR DESCRIPTION
**Pull request by petemoore**
Curious if we can remove these libraries.

### CODE REVIEW

**Comment by petemoore** [comment]
Doesn't look like we're ready to get rid of them quite yet

**Comment by lotas** [comment]
@petemoore this is probably fine to remove, can you reabase to see what tests would fail? I think none of them should

**Review by matt-boris — APPROVED** [review]
It's a shame you needed to add three more lines to the monorepo 😉

**Review by lotas — APPROVED** [review]
zero tests failed? amazing!

**Comment by djmitche** [comment]
You may want to remove https://docs.taskcluster.net/docs/reference/platform/auth/api#azure-credentials as well (at least azureContainerSAS)

**Pull request merged**
