### PR TITLE
Rewrite DB v49

### PR DESCRIPTION
**Pull request by helfi92**
From https://github.com/taskcluster/taskcluster/issues/3632, the agreement here is that we will migrate a single table at a time to avoid having the migration script hang.

Relates to https://github.com/taskcluster/taskcluster/issues/3632.

### CODE REVIEW

**Comment by djmitche** [comment]
49's already been released, so it can't be rewritten.  I think it's just a learning experience at this point.

**Comment by helfi92** [comment]
Are we planning to do the migration during a tree closure window in that case?

**Comment by djmitche** [comment]
@sciurus can confirm, but I think the migration is complete now.  Once the lock was cleared by killing the crontask, it went quickly.

**Comment by sciurus** [comment]
Right, this migration is done in all environments, so this PR is not needed.

It looks in this PR like you changed the migrations to do each table in its own transaction, which I agree is the correct approach for migrations that require an exclusive lock.

**Comment by helfi92** [comment]
Ah, great to hear. Thanks folks.

**Pull request closed without merging**
