### PR TITLE
Bug #286 [UI] Reopen the section menu when clicking "next" 

### PR DESCRIPTION
**Pull request by sudipt1999**
I would really thank the @helfi92 and @iFlameing  for helping me out in this bug ! 
I have tested out the commit on localhost ! Kindly please review it.

### CODE REVIEW

**Comment by sudipt1999** [comment]
Sure @helfi92

**Comment by sudipt1999** [comment]
Kindly run again the taskgroup since it is showing due to connectivity it fail this time @helfi92

**Comment by helfi92** [comment]
I think there's linting issues:


screen shot 2019-02-28 at 4 08 22 pm

**Comment by sudipt1999** [comment]
I fixed it and commited also ! Kindly run the taskgroup again ! That time
it gave network connectivity error

**Comment by sudipt1999** [comment]
Its says something about maximum word in a line! Will correct It

**Comment by helfi92** [comment]
You should be able to fix most linting issues with `yarn lint --fix`.

**Comment by sudipt1999** [comment]
Task group shows this error but I already added a space to it.
screenshot from 2019-03-01 02-17-29
screenshot from 2019-03-01 02-19-05

**Comment by sudipt1999** [comment]
@helfi92  I am making new pr closing this one !

**Comment by djmitche** [comment]
@sudipt1999 please remember to ensure the linting errors are fixed before requesting review :)

**Pull request closed without merging**
