### PR TITLE
[UI/Enhancement] Add a way to jump to a task ID/task group from the log viewer in less clicks

### PR DESCRIPTION
**Pull request by ss77995ss**
### Description
* Related Issue #818 
* Move `Raw Log`  button into a `SpeedDial` component
* Add `View Different Task` button in `SpeedDial` to let users go to different tasks

### CODE REVIEW

**Comment by ss77995ss** [comment]
Hi @helfi92 , I just updated this PR, please help me review it if you have time, thanks!

**Comment by ss77995ss** [comment]
Screen Shot 2019-08-08 at 21 13 57

Just make sure this is the expected position of the buttons, right?

**Comment by helfi92** [comment]
Yep.

**Comment by ss77995ss** [comment]
@helfi92 , I just updated the PR, please check, thanks!

**Pull request merged**
