### PR TITLE
chore: improve eslint rules

### LINKED ISSUE #7246: Improve eslint formatting
We probably can add few more rules to make code read better:

- spacing around keywords (`if (cond) { .. }`)
- space inside parens `(cond)` (instead of `( cond )`)

subjective and debatable though

### PR DESCRIPTION
**Pull request by thakkarujas5**
Fixes #7246 

- Add rule for spaces before and after keywords.
- Add rule to remove spaces inside round parenthesis.

### CODE REVIEW

**Comment by petemoore** [comment]
This looks great so far, many thanks for this @thakkarujas5 ! :-)

**Comment by petemoore** [comment]
> > This looks great so far, many thanks for this @thakkarujas5 ! :-)
> 
> I am confused about the second suggestion of the issue, do we want spaces inside round braces ( cond ) or not because we are already adding spaces around keywords which would make the condition look like this if ( cond ) {..}.

This is a good question. When Yarik wrote:

> - space inside parens `(cond)` (instead of `( cond )`)

my interpretation is that "space inside parens" refers to which setting should be adjusted (i.e. the amount of space inside parentheses) and that the setting should be set to match his example (i.e. no space). That would be my preference too. Thanks Ujas!

**Review by petemoore — APPROVED** [review]
This looks great, thank you so much Ujas, the contribution is really appreciated! ⭐ 🚀

**Comment by petemoore** [comment]
@thakkarujas5 If you are interested in getting more involved with taskcluster, please note we have a matrix channel [here](https://chat.mozilla.org/#/room/#taskcluster:mozilla.org) and we have community meetings [here](https://github.com/taskcluster/taskcluster/discussions/5036#discussion-3783425). You are always welcome to join us, if you have time/interest.

**Comment by thakkarujas5** [comment]
> @thakkarujas5 If you are interested in getting more involved with taskcluster, please note we have a matrix channel [here](https://chat.mozilla.org/#/room/#taskcluster:mozilla.org) and we have community meetings [here](https://github.com/taskcluster/taskcluster/discussions/5036#discussion-3783425). You are always welcome to join us, if you have time/interest.

Hi Pete, I am already part of the matrix channel, I was working on a issue with Yarik, but since he is on PTO, I picked up another small issue that did not require any dependency :)

**Comment by petemoore** [comment]
> > @thakkarujas5 If you are interested in getting more involved with taskcluster, please note we have a matrix channel [here](https://chat.mozilla.org/#/room/#taskcluster:mozilla.org) and we have community meetings [here](https://github.com/taskcluster/taskcluster/discussions/5036#discussion-3783425). You are always welcome to join us, if you have time/interest.
> 
> I am not sure why two checks are failing, is it due to any issue in code?

It looks like it is missing [this](https://github.com/taskcluster/taskcluster/commit/e8ebd85cc630a90fceb3b717983bb951d0c2d69c#diff-518248e5500f9387e8a41f99e13c83f545a4bbb9f9592d7609132d7dc8f41d34R21). I'll update the branch, that should fix it. Thanks Ujas, and now I see indeed you contributed all the nice new github features!

Feel free to add yourself to [the contributors file](https://github.com/taskcluster/taskcluster/blob/main/.all-contributorsrc) if you wish to show up in the [contributors section](https://github.com/taskcluster/taskcluster/?tab=readme-ov-file#contributors). Many thanks!

**Comment by petemoore** [comment]
@all-contributors please add @thakkarujas5 for code

**Comment by petemoore** [comment]
> @petemoore
> 
> I've put up [a pull request](https://github.com/taskcluster/taskcluster/pull/7353) to add @thakkarujas5! 🎉

@thakkarujas5 Before I merge this, let me know if this is ok with you! Thanks :-)

**Comment by thakkarujas5** [comment]
> > @petemoore
> > I've put up [a pull request](https://github.com/taskcluster/taskcluster/pull/7353) to add @thakkarujas5! 🎉
> 
> @thakkarujas5 Before I merge this, let me know if this is ok with you! Thanks :-)

Sure, that would be great :)

**Pull request merged**
