### PR TITLE
[UI] Add CopyToClipboardListItem

### PR DESCRIPTION
**Pull request by helfi92**
Relates to https://github.com/taskcluster/taskcluster/issues/2127.

### CODE REVIEW

**Comment by helfi92** [comment]
@aryamanpuri, we would need to create a `CopyToClipboardTableCell` component to handle the cases where we use CopyToClipboard with the TableCell compoent (rather than ListItem). Do you want to work on it?

**Comment by aryamanpuri** [comment]
> @aryamanpuri, we would need to create a `CopyToClipboardTableCell` component to handle the cases where we use CopyToClipboard with the TableCell compoent (rather than ListItem). Do you want to work on it?

Yes sure, can you describe more about to be done in this

**Comment by helfi92** [comment]
> Yes sure, can you describe more about to be done in this

The change will be required in the following files:

```
> git grep "<CopyToClipboard "

src/components/WMErrorsTable/index.jsx:        <CopyToClipboard title={`${reported} (Copy)`} text={reported}>
src/components/WMWorkersTable/index.jsx:        <CopyToClipboard title={`${workerAge} (Copy)`} text={workerAge}>
src/components/WorkerTable/index.jsx:              <CopyToClipboard title={task.started} text={task.started}>
src/components/WorkerTable/index.jsx:              <CopyToClipboard title={task.resolved} text={task.resolved}>
src/components/WorkersTable/index.jsx:            <CopyToClipboard title={`${firstClaim} (Copy)`} text={firstClaim}>
```

The change will consist of using a new component "CopyToClipboardTableCell". https://firefox-ci-tc.services.mozilla.com/provisioners/app-services-1/worker-types/b-linux is an example where you can see the copy component inside a table cell.

**Comment by aryamanpuri** [comment]
Okay I am looking upon this .

**Comment by aryamanpuri** [comment]
WMErrorsTable/index.jsx is different from others as
>  <TableCell>
            <TableCellItem button>
              <ListItemText
                className={classes.errorReported}
                disableTypography
                primary={
                  <Typography variant="body2">
                    <DateDistance from={reported} />
                  </Typography>
                }
              />
              <ContentCopyIcon size={iconSize} />
            </TableCellItem>
          </TableCell>

Whereas other are of 
>  <TableCell>
                  <TableCellItem button>
                    <DateDistance from={latestTask.run.started} />
                    <ContentCopyIcon
                      className={classes.linksIcon}
                      size={iconSize}
                    />
                  </TableCellItem>
                </TableCell>
              </CopyToClipboard>

How to include both in one go ?

**Comment by helfi92** [comment]
You should be able to do the following diff:

```diff
diff --git a/ui/src/components/WMErrorsTable/index.jsx b/ui/src/components/WMErrorsTable/index.jsx
index c661dcb73..977b50346 100644
--- a/ui/src/components/WMErrorsTable/index.jsx
+++ b/ui/src/components/WMErrorsTable/index.jsx
@@ -63,9 +63,6 @@ import { pageInfo, WMError } from '../../utils/prop-types';
     top: theme.spacing(1),
     right: theme.spacing(1),
   },
-  errorReported: {
-    paddingRight: theme.spacing(2),
-  },
 }))
 export default class WorkerManagerErrorsTable extends Component {
   static propTypes = {
@@ -188,15 +185,9 @@ export default class WorkerManagerErrorsTable extends Component {
         <CopyToClipboard title={`${reported} (Copy)`} text={reported}>
           <TableCell>
             <TableCellItem button>
-              <ListItemText
-                className={classes.errorReported}
-                disableTypography
-                primary={
-                  <Typography variant="body2">
-                    <DateDistance from={reported} />
-                  </Typography>
-                }
-              />
+              <Typography variant="body2">
+                <DateDistance from={reported} />
+              </Typography>
               <ContentCopyIcon size={iconSize} />
             </TableCellItem>
           </TableCell>
```

**Comment by aryamanpuri** [comment]
> <TableCell>
        <TableCellItem button>
        <TableCellItem
          button
          secondary={secondary}
          {isCopy ? <CheckIcon /> : <ContentCopyIcon size={IconSize} />}
        </TableCellItem>
          {...TableCellItemProps}
          {...(isCopy ? <CheckIcon /> : <ContentCopyIcon size={IconSize} />)}
        />
      </TableCell>
What is wrong in it?
It is not rendering

**Comment by aryamanpuri** [comment]
> <TableCell>
        <TableCellItem button>
        <TableCellItem
          button
          secondary={secondary}
          {...TableCellItemProps}
          {...(isCopy ? <CheckIcon /> : <ContentCopyIcon size={IconSize} />)}
        />
What is wrong in it ? It is not rendering

      </TableCell>

**Comment by helfi92** [comment]
Probably one of the props in TableCellItem is not defined. The definition of that component can be found in `src/components/TableCellItem`.

**Comment by aryamanpuri** [comment]
Screenshot from 2019-12-23 22-37-32

Looks good
Can you help what to do in the changelog ?

**Comment by helfi92** [comment]
From the taskcuster root directory, you can run:

```
yarn changelog --silent --no-bug
```

then you'll need to commit and push the generated file.

**Comment by aryamanpuri** [comment]
> yarn changelog --silent --no-bug
Nice , didn't know about it ! Thanks

**Pull request merged**
