### PR TITLE
[UI]: Changing icon for create task

### LINKED ISSUE #1884: [UI] Choose more appropriate "create task" icon
**Describe the bug**
The "create task" button currently uses the floppy disk save icon. While this is somewhat appropriate, it doesn't really feel right for creating a task. I think (although others can disagree with me) that something with the feeling of "starting", "running", "go", "schedule", etc would make sense.

If my spelunking of the issues is correct, https://materialdesignicons.com is where our icons come from. Does this issue and that link make senes, @helfi92? If this is frivilous feel free to close :laughing: 

**To Reproduce**

1. Go to https://community-tc.services.mozilla.com/tasks/create
2. Observe the green floppy disk circle in the lower right

**Screenshots**
image

### PR DESCRIPTION
**Pull request by vishakhanihore**
Github Bug/Issue: Fixes #1884

### CODE REVIEW

**Comment by vishakhanihore** [comment]
@helfi92 @djmitche Taskcluster CI didn't fire up? Is it down or any other issue?

**Comment by djmitche** [comment]
It was down due to an Azure outage.

**Comment by vishakhanihore** [comment]
@djmitche Can you restart the build ?

**Comment by vishakhanihore** [comment]
@helfi92 @djmitche Since I have submitted my application and its around a
month waiting for the annoncement of selected interns. We can contribute in
this waiting time or not?

**Comment by helfi92** [comment]
> We can contribute in
this waiting time or not?

Contributions are always welcome and appreciated.

**Pull request closed without merging**
