### PR TITLE
Rename CLI login client_id to name and add slugId to avoid resetting token

### PR DESCRIPTION
**Pull request by ededals**
Issue #1758

### CODE REVIEW

**Comment by djmitche** [comment]
Oh, and you'll need to add a changelog entry.  See https://github.com/taskcluster/taskcluster/blob/master/dev-docs/best-practices/changelog.md.  I'd consider this a "minor" update as it adds significant new functionality.

**Comment by helfi92** [comment]
I'm having trouble running this. Something like `go run main.go signin` throws:

```
➜  client-shell git:(master) go run main.go signin
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/taskcluster/taskcluster/clients/client-shell/config.Setup()
	/Users/haali/Documents/Mozilla/projects/taskcluster/clients/client-shell/config/init.go:53 +0x61f
main.main()
	/Users/haali/Documents/Mozilla/projects/taskcluster/clients/client-shell/main.go:12 +0x22
exit status 2
```

This is my first time running the client-shell locally so it's very possible I'm doing something wrong. @ededals @djmitche Would you have to know why this is happening. I'm running go version `go1.12.9` darwin/amd64 which was installed using gvm. fwiw, `yarn generate` which tells me that go is properly installed.

**Comment by ededals** [comment]
@helfi92 I do not know if this will be of any use, but  did build a binary first by going to shell-client root directory and running ```go build -o taskcluster```. Then after ```./taskcluster signin``` everything seemed to work fine. I am using ```go version go1.13.3 linux/amd64``` by the way

**Comment by helfi92** [comment]
How is it going @ededals? Did you have any questions for me? We should plan on finishing this implementation soon. I can help with something if that's more convenient.

**Comment by ededals** [comment]
Hey @helfi, I would like to try to handle this, as I like how this is turning out, but during weekdays between family and work it is difficult to find time. I would like to do it on weekend. If this is too late, I can modify just signin.go

**Comment by helfi92** [comment]
The weekend is perfect :) All yours! Thanks for your help :)

**Comment by ededals** [comment]
@helfi92 was thinking on how to get login state. What I came up with was to use this query ```ui/src/App/isLoggedIn.graphql``` on client prop. and use it in ```ui/src/views/ViewClient/index.js``` to check if user is logged in. Does this sound right to you? Is there some better way I should cinsider?

**Comment by helfi92** [comment]
> @helfi92 was thinking on how to get login state. What I came up with was to use this query `ui/src/App/isLoggedIn.graphql` and use it in `ui/src/views/ViewClient/index.js` on client prop, to check if user is logged in. Does this sound right to you? Is there some better way I should consider?

That sounds good to me.

**Comment by ededals** [comment]
Hey @helfi92,
 
In the end I decided to use Auth context to check logged in user.
I hope I have not missed anything.

**Pull request merged**
