### PR TITLE
Created requirements.txt

### PR DESCRIPTION
**Pull request by Patil2099**
#749

### CODE REVIEW

**Comment by escapewindow** [comment]
Thank you for this PR!

First off, what problem are we trying to solve here? The requirements are listed in `setup.py`, both for installation and testing. We automatically install the install requirements on installation of the python client; we automatically install the test requirements on running `tox` to run the tests. Is there another use case you're trying to solve for?

If we want to land requirements file(s):

1. These are the test requirements, not the install requirements. I generally expect to find install requirements at requirements.txt, if any. We could deal with that by having a requirements.txt and a requirements-test.txt. In releng we've dealt with that via [pip-compile-multi](https://pypi.org/project/pip-compile-multi/), meaning we would have a `requirements/base.in` and a `requirements/test.in` that we compile into `requirements/base.txt` and `requirements/test.txt` (or even `requirements/base-py36.txt` etc.). However, two static files work, as long as they're maintained.
2. if we have a requirements.txt (or multiple), then ideally it would be the source of truth. That means we should change `setup.py` to read from the `requirements.txt`, and we would need to update the packaging to include `requirements.txt`. This would be true for `requirements-test.txt` as well.

**Comment by Patil2099** [comment]
> Thank you for this PR!
> 
> First off, what problem are we trying to solve here? The requirements are listed in `setup.py`, both for installation and testing. We automatically install the install requirements on installation of the python client; we automatically install the test requirements on running `tox` to run the tests. Is there another use case you're trying to solve for?
> 
> If we want to land requirements file(s):
> 
> 1. These are the test requirements, not the install requirements. I generally expect to find install requirements at requirements.txt, if any. We could deal with that by having a requirements.txt and a requirements-test.txt. In releng we've dealt with that via [pip-compile-multi](https://pypi.org/project/pip-compile-multi/), meaning we would have a `requirements/base.in` and a `requirements/test.in` that we compile into `requirements/base.txt` and `requirements/test.txt` (or even `requirements/base-py36.txt` etc.). However, two static files work, as long as they're maintained.
> 2. if we have a requirements.txt (or multiple), then ideally it would be the source of truth. That means we should change `setup.py` to read from the `requirements.txt`, and we would need to update the packaging to include `requirements.txt`. This would be true for `requirements-test.txt` as well.

It was for testing.

**Comment by escapewindow** [comment]
Something like `tox --develop --notest` will create virtualenvs in `.tox/py{27,36,37}` with all the test dependencies installed. Does that work for you?

**Comment by djmitche** [comment]
It sounds like agreement is to not do this..

**Pull request closed without merging**
