### PR TITLE
Support amqp (without TLS) for communicating with pulse

### LINKED ISSUE #4648: Make it so that you can specify rabbitmq to use TLS or not
Some people, especially in development deployments, may want to do a simple RabbitMQ installation with no SSL, this issue is there so we can make this possible.

### PR DESCRIPTION
**Pull request by djmitche**
Github Bug/Issue: Fixes #4648

I'll test this out in my dev deployment.

### CODE REVIEW

**Comment by djmitche** [comment]
This worked for me locally.  Note (as it confused me for a bit!) that amqp / port 5672 works on the hip-macaw cluster but not on the orange-antelope cluster!

**Review by petemoore — APPROVED** [review]
Looks about right to me. Thanks!

Does it also look OK to you @MasterWayZ?

**Comment by djmitche** [comment]
I'll merge, but I will make another PR if the answer is "no" :)

**Comment by MasterWayZ** [comment]
It does look good, though the TLS/non-TLS port can be confusing. (It did for me).

**Pull request merged**
