### PR TITLE
Add responsiveness to smaller width screens for tables

### LINKED ISSUE #5379: UI: Worker pools table is not responsive
Table on the [worker-manager](https://community-tc.services.mozilla.com/worker-manager) page has limited width and not responsive. Content is being hidden.

image

TODO:
* trim column widths to fit initial content (since whole content is limited at `~1600px`)
* make table responsive (maybe even hide some columns, i.e. email of the owner)

### PR DESCRIPTION
**Pull request by ahmedDevs**
Github Bug/Issue: Fixes #5379

### CODE REVIEW

**Comment by lotas** [comment]
hey @ahmedDevs thanks for submitting! We were all away for a week, we'll review it shortly ;)

**Comment by lotas** [comment]
Hey again @ahmedDevs, it looks great!
I just spotted one weird "font jump" situation when going from
image
to
image

so around 1500px breakpoint

Otherwise looks great, thanks!

**Comment by ahmedDevs** [comment]
Hey @lotas, thanks for pointing that out. I've removed the font jump.

**Comment by lotas** [comment]
> Hey @lotas, thanks for pointing that out. I've removed the font jump.

great, thanks!
Can you please check this linter error: https://github.com/taskcluster/taskcluster/pull/5683/checks?check_run_id=8812225206 
and then we can merge it

**Comment by lotas** [comment]
Actually noticed there are some resolutions that make some table not stretch, or at least they are using different containers with the filter input: 
image

or maybe that's the problem of those Virtualized tables hm

**Comment by ahmedDevs** [comment]
Hey, I took care of the linter error. As for the tables that are not stretching at some resolutions, I'm gonna look it up further.

**Comment by lotas** [comment]
hey @ahmedDevs is there anything you would like to add to this PR still? Or we can rebase branch and merge it already?

Thanks

**Comment by ahmedDevs** [comment]
Looks good, I think it does what it's supposed to in terms of responsiveness as far as tables go :)

**Comment by lotas** [comment]
> Looks good, I think it does what it's supposed to in terms of responsiveness as far as tables go :)

awesome! Can you please rebase before we would be able to merge it?

**Comment by ahmedDevs** [comment]
Done

**Pull request merged**
