### PR TITLE
 [UI] next/prev icon in light theme 

### PR DESCRIPTION
**Pull request by aryamanpuri**
I have changed the color of the Left and Right arrow Icons as required.
@helfi92 Have a look.
#1773

### CODE REVIEW

**Comment by aryamanpuri** [comment]
@helfi92  I will change the pull-request title. Can you please elaborate on what I have to do further.

**Comment by helfi92** [comment]
> Do I just have to implement the changes made by you?

Yep.

**Comment by helfi92** [comment]
Tests are failing. Run `yarn lint --fix` inside the `ui` directory.

**Comment by aryamanpuri** [comment]
@helfi92  How to handle this error 

error taskcluster-ui@21.3.0: The engine "node" is incompatible with this module. Expected version "10.16.3". Got "12.13.0"

**Comment by helfi92** [comment]
> The engine "node" is incompatible with this module. Expected version "10.16.3". Got "12.13.0"

It means your node version is not 10.16.3. You can use https://github.com/nvm-sh/nvm to easily switch between nod versions. It's pretty convenient.

**Comment by aryamanpuri** [comment]
> +1 Thank you!
> 
> _Note: Will merge after #1729_
Any other work to do, please assign me.

**Comment by aryamanpuri** [comment]
@helfi92  Should I make a new pull request. I have forced pushed which have deleted all my commits.

**Comment by helfi92** [comment]
The next/previous button should be in a PR and then the cancel action in another. Mistakes happen. That's how we all learn :)

**Pull request closed without merging**
