### PR TITLE
Change firedBy to enum

### PR DESCRIPTION
**Pull request by Biboswan**
#466

### CODE REVIEW

**Comment by Biboswan** [comment]
oh i missed something

**Comment by djmitche** [comment]
Ah, and I see now they did not.  Also, this will need a run of `yarn generate`.  Then it should be good to merge :)

**Comment by Biboswan** [comment]
We use firedBy 'test'. Now I remember why I kept it any string. So the fix is to add a `test` enum as well in the schema ?

**Comment by djmitche** [comment]
Probably better to change the tests to use an allowed value.

**Pull request merged**
