### PR TITLE
Fix the example value for `registered_clients` in the dev config

### PR DESCRIPTION
**Pull request by Eijebong**
It's not expecting a map but a list. If you copied the previous value,
the web-server service wouldn't start and give this error:
`cfg.login.registeredClients.map is not a function`

### CODE REVIEW

**Review by petemoore — CHANGES_REQUESTED** [review]
Many thanks for this! Unfortunately, the CI failed, and it looks like this is because the change gets overwritten when `yarn generate` is called. I think the change will need to made in infrastructure/tooling/src/generate/generators/k8s.js or some associated file that it uses.

**Comment by Eijebong** [comment]
Woops, this completely slipped out of my mind. CI should be happier now.

**Comment by djmitche** [comment]
(that client-rust failure is an intermittent)

**Comment by petemoore** [comment]
@Eijebong I only see the changelog file now, but no code changes - can you take a look? Many thanks.

**Comment by djmitche** [comment]
I pushed an update at https://github.com/djmitche/taskcluster/pull/new/fix-dev-config-example that should enable this.  It's worth looking for other config values that have the wrong type and adding them to the list.

**Comment by petemoore** [comment]
> I pushed an update at https://github.com/djmitche/taskcluster/pull/new/fix-dev-config-example that should enable this. It's worth looking for other config values that have the wrong type and adding them to the list.

Hi @djmitche, are you going to create that as a separate PR, or should @Eijebong include that change in this PR? Thanks!

**Comment by djmitche** [comment]
Please pull it into this PR.  I'm not a maintainer anymore so I can't push to this PR.

**Comment by djmitche** [comment]
@petemoore do you want to have another look?  Are there other fields that should be included in this list?

**Review by petemoore — APPROVED** [review]
Looks great, many thanks!

**Comment by djmitche** [comment]
I'm just a lowly contributor now, so you'll have to click for me!
image

**Comment by petemoore** [comment]
@djmitche Is the rust client failure the same intermittent? And any idea about the python client failure?

**Comment by djmitche** [comment]
The Python failure was temporary (but #5015  and #4614!), and yes, it's the same rust intermittent.

**Pull request merged**
