### PR TITLE
[Bug 1579065] Upgrade to hapi/hawk

### PR DESCRIPTION
**Pull request by vishakhanihore**
Bugzilla Bug: [1579065](https://bugzilla.mozilla.org/show_bug.cgi?id=1579065)

### CODE REVIEW

**Comment by vishakhanihore** [comment]
@djmitche @helfi92 Please Review 😄

**Comment by djmitche** [comment]
Hm, green tests are good!  I really don't trust the Hawk authors, so I want to have a deeper look at this, since it's critical to the Taskcluster security model.  Since we are coming up on a major deadline, this may sit for a few weeks until I have the time to do so, and until I'm comfortable landing something so critical and with such high potential for breakage.  So, thank you, and apologies for the long wait.

**Comment by vishakhanihore** [comment]
Sounds good. Production should not break😁

**Comment by vishakhanihore** [comment]
@djmitche Any updates on it ?

**Comment by djmitche** [comment]
Nope, I don't want to merge something this risky until after November 9.

**Comment by vishakhanihore** [comment]
> Nope, I don't want to merge something this risky until after November 9.

No issues will ping you on 9 November 😆

**Comment by vishakhanihore** [comment]
@djmitche

**Comment by djmitche** [comment]
You are punctual :)

**Comment by vishakhanihore** [comment]
Sure, I will change in clients too.

**Comment by vishakhanihore** [comment]
> hawk

There is no `yarn.lock` for it @djmitche . Am I getting something wrong here ?

**Comment by djmitche** [comment]
It's here:
```
https://github.com/taskcluster/taskcluster/blob/42b8948ebfab8ab5588f63084fa3d9ebe08e5e4b/yarn.lock#L3785-L3794
```
and `yarn why` tells me it's reqiured by clients/client.

**Comment by vishakhanihore** [comment]
@djmitche Please re-review

**Comment by djmitche** [comment]
That's a bunch of red X's.. looks like client/client needs to be updated to require @hapi/hawk.

**Comment by vishakhanihore** [comment]
I will look into it tonight.

**Comment by vishakhanihore** [comment]
@djmitche green ticks finally ❤️

**Comment by djmitche** [comment]
Thank you!  That's a great improvement :D

**Comment by vishakhanihore** [comment]
@helfi92 Review Please

**Pull request merged**
