### PR TITLE
Issue 6277 - stop releasing Generic Worker simple engine binaries

### LINKED ISSUE #6277: Stop releasing simple engine
We continue to hit issues in production from usage of the simple engine, for example [Bug 1832366](https://bugzilla.mozilla.org/show_bug.cgi?id=1832366).

There is no reason to release a simple engine binary. The simple engine is useful for local dev deployments, and for running unit tests. Neither of these require the release binaries, since a dev deployment (docker compose) uses a docker container where the generic-worker simple engine binary is built in the docker image from source, and the tests build the test binary directly too.

Therefore, we can simply stop releasing the simple engine binaries, and everything should continue to function that requires the simple engine for dev purposes.

### PR DESCRIPTION
**Pull request by petemoore**
Fixes #6277

### CODE REVIEW

**Comment by petemoore** [comment]
Staging release in progress here: https://github.com/taskcluster/staging-releases/tree/staging-release/v52.0.0

**Review by lotas — APPROVED** [review]
LGTM

**Comment by petemoore** [comment]
Staging release failed with:

```
Error: Nonzero exit status 1; see /task_168560796636020/taskcluster/release-debug-logs/livelog-docker-build.log for details (while executing task Build livelog Docker Image)
    at ChildProcess.<anonymous> (/task_168560796636020/taskcluster/infrastructure/tooling/src/utils/command.js:62:16)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
error Command failed with exit code 1.
```

CI failure above was unrelated to this PR, and tracked in issue #6280.

**Comment by petemoore** [comment]
> I will look into this, to see if it is related to this PR. At first glance, it also appears to be coincidental, since it is is about the Live Log docker container build, which should not depend on Generic Worker binaries, but who knows ...

Indeed, it was unrelated - `apt-get upgrade -y` [failed](https://community-tc.services.mozilla.com/tasks/eCLrkYVRRtmm6bwuPdYSPg/runs/0/logs/debug-logs/livelog-docker-build.log):

```
------
Dockerfile:3
--------------------
   1 |     FROM ubuntu:latest AS certs
   2 |     RUN apt-get update
   3 | >>> RUN apt-get upgrade -y
   4 |     RUN apt-get install -y ca-certificates
   5 |     RUN mkdir /empty
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get upgrade -y" did not complete successfully: exit code: 4294967295
```

**Comment by petemoore** [comment]
Bizarrely the [reported exit code 4294967295](https://community-tc.services.mozilla.com/tasks/eCLrkYVRRtmm6bwuPdYSPg/runs/0/logs/debug-logs/livelog-docker-build.log#L146) appears to be a Windows exit code, not a Linux one. Yet this ran on a Linux worker.

**Comment by petemoore** [comment]
I'll make another staging release, and see what happens....

**Pull request merged**
