### PR TITLE
Update TaskDefinition/index.jsx and added some margin for JsonDisplay component 

### PR DESCRIPTION
**Pull request by vishal-sharma-369**
solves: #6599

Added some margin for JsonDisplay component in TaskDefinition/index.jsx file.

### CODE REVIEW

**Comment by lotas** [comment]
hi @vishal-sharma-369  and thanks for the quick fix!

Would you mind why this page is any different than the others? Maybe some wrapper or parent class is missing, because it seems like other pages aren't affected. 
Could be nice to avoid using direct margin usage in component if possible. 
Thanks!

**Comment by petemoore** [comment]
Many thanks for this @vishal-sharma-369!

* The macOS generic worker issue was an intermittent issue, I've retriggered that task.
* The changelog error is genuine - there are some docs about how to resolve that [here](https://github.com/taskcluster/taskcluster/blob/8664061ff65bdd1b274d1a765db4d5f452ba8883/dev-docs/best-practices/changelog.md).

Good luck, and shout if you get stuck! :-)

**Comment by lotas** [comment]
Oh, I'm sorry, I just realised this is also a responsive layout issue, and for some breakpoints it works fine, for some not.
image

**Comment by lotas** [comment]
I will close this PR for now as it doesn't fully resolve the problem. Please feel free to reopen. Thanks

**Pull request closed without merging**
