### PR TITLE
Introduce secrets in services configurations and add ConfigMap resource

### LINKED ISSUE #7036: Separate Sensitive Secret Values from Plain Configuration Values in Kubernetes Secrets
Currently, all configuration values are being placed in secrets instead of using ConfigMaps for plain configuration. This approach increases the number of secrets unnecessarily.

Could you make changes to separate the configuration values, reducing the number of secrets? I see that the secrets are generated by a JS script that reads the contents of service config.yaml files.

Separating the configuration into ConfigMaps where possible would make managing configuration data and secrets easier.

### PR DESCRIPTION
**Pull request by lotas**
This introduces changes to services configuration by adding `:secret` flag support.

Environment variables marked as `!env:*:secret(:optional)?` would be treated as such, and will be used in `kind: Secret` resources in kubernetes.
All other values, that are not marked as secrets, would be treated as non-sensitive configuration values, and as such will be deployed as `ConfigMap` resources in kubernetes.

This also updates deployments and cronjobs to pull environment variables from both secrets and configmaps.

This is a breaking change, since configuration is being changed, and new deployment resource type is being added. 

Existing deployments shouldn't be affected as long as they didn't do anything around secrets files.

Fixes #7036

### CODE REVIEW

**Comment by lotas** [comment]
Tested generation steps locally, and checked generated templates with `yarn dev:templates`

Also applied generated helm chart to the local kubernetes service, it didn't fail :)

**Review by petemoore — DISMISSED** [review]
Fine from my side, but I can't claim to really understand it.

**Review by petemoore — APPROVED** [review]

**Review by petemoore — APPROVED** [review]
@Eijebong / @djmitche / @aaskat
I'm not too confident reviewing this, if any of you have feedback, feel free to add it here. Thanks!

**Comment by aaskat** [comment]
@lotas Tested in ArgoCD, it is working as expected. Is it possible to mark 'pulse_username' as a secret and make secrets optional in the Helm chart as well? Currently, I specify an empty string for 'write_db_url' as a placeholder because Helm requires it and fails when disabling secrets and creating a new secret with new values.

**Comment by lotas** [comment]
> @lotas Tested in ArgoCD, it is working as expected. Is it possible to mark 'pulse_username' as a secret and make secrets optional in the Helm chart as well? Currently, I specify an empty string for 'write_db_url' as a placeholder because Helm requires it and fails when disabling secrets and creating a new secret with new values.

thanks for testing it @aaskat 

`pulse_username` can be added yes

Ah, I haven't thought about secrets being optional (in #7056) but helm not getting those values would be upset.
I'll check.

**Comment by aaskat** [comment]
@lotas when you planing to merge this feature?

**Comment by lotas** [comment]
> @lotas when you planing to merge this feature?

I've updated PR to include PULSE_USERNAME into secrets, but the second issue with schema validation and missing values is not yet solved.

**Comment by lotas** [comment]
I've created a separate issue for schema https://github.com/taskcluster/taskcluster/issues/7159 
Quickly experimented with if/then/else in schema, but it doesn't work yet as expected

**Review by petemoore — APPROVED** [review]
lgtm, thanks Yarik!

**Pull request merged**
