### PR TITLE
Allow taskQueueId in task definitions

### LINKED ISSUE #3580: allow taskQueueId in task definitions, return it along with provisionerId/workerType

### PR DESCRIPTION
**Pull request by alopezz**
Github Bug/Issue: Fixes #3580

I'm not completely sure of all the places that taskQueueId should appear alongside the old identifiers.

I'm guessing that other than what I've done so far I should add it to task statuses as well?

### CODE REVIEW

**Comment by djmitche** [comment]
> I'm guessing that other than what I've done so far I should add it to task statuses as well?

Yes, that sounds correct.  We want to delete workerPool and providerId properties eventually, so we'll need taskQueueId everywhere those appear.

**Review by djmitche — COMMENTED** [review]
Looks great!  Toss in a changelog, and this should be good to go!  I think that can be a minor changelog -- the Go client's structs change, but only to add a field, which shouldn't cause any issues.

What do you think about adding a sentence about deprecation to the providerId / workerType properties in the schema?

**Comment by alopezz** [comment]
> Looks great! Toss in a changelog, and this should be good to go! I think that can be a minor changelog -- the Go client's structs change, but only to add a field, which shouldn't cause any issues.

Actually I'm not finished yet as there are still places where I haven't added the identifier. I'll soon commit the changes involving the status and some other case, but there is one case that I'm not sure how to handle, which is for task creation (`create-task-request.yml`). I think it's the only place where it's the client who would have to add the new field, and I'm not sure what's expected here.

> What do you think about adding a sentence about deprecation to the providerId / workerType properties in the schema?

Will do.

**Comment by djmitche** [comment]
Haha, well, I shouldn't have assumed ;)

For the client-provided value, I think allow
* provisionerId and workerType; or
* taskQueueId; or
* all three, as long as they match

I know that's a bit of work, but I think it's maximally compatible -- the last point covers the case where someone calls `queue.task`, modifies the result, and calls `queue.createTask` with it.

**Comment by alopezz** [comment]
Having a look at the things that are failing, I suspect that the go client code is not being generated correctly for the changes I made on the Task Definition Request schema, very probably due to the use of `anyOf` that tries to encode the two ways to satisfy the requirement.

My knowledge of Go is limited, but this doesn't look good:

https://github.com/taskcluster/taskcluster/blob/ba3a2ee3eac57e60278641838668f4395cda9b98/clients/client-go/tcqueue/types.go#L821-L829
https://github.com/taskcluster/taskcluster/blob/ba3a2ee3eac57e60278641838668f4395cda9b98/clients/client-go/tcqueue/types.go#L1009-L1010

**Comment by djmitche** [comment]
Yeah, that's always been a bit janky.  And even outside of Go, json-schema's ability to enforce complex schema requirements like this with intelligible error messages is limited at best.  It might be best to just add all three fields as "regular" and optional fields, and do the "either or matching both" check in JS.  That will also limit the number of non-compatible changes to the Go data structures to one (when `WorkerType` and `ProvisionerId` are removed).

**Comment by alopezz** [comment]
I don't know why those tests are failing...

**Comment by petemoore** [comment]
Should the `anyOf` be `oneOf` ?

**Comment by petemoore** [comment]
> I don't know why those tests are failing...

The only failure I see is the missing changelog:

```
$ node infrastructure/tooling/src/main.js changelog:check --pr 4217
Changelog OK
ERROR: Pull Request 4217 does not modify any files in 'changelog/'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by djmitche** [comment]
The missing secrets are a result of some credentials rotation we did recently. A rebase will fix it, or just ignore `service-auth` on this PR.  Sorry!

**Comment by alopezz** [comment]
Everything's green now after rebasing.

**Review by djmitche — APPROVED** [review]
It looks good to me.  @petemoore do you see any issues with this?

**Comment by djmitche** [comment]
Ah, I think @petemoore is away at the moment.  Let's get this landed before it develops conflicts ;)

**Comment by petemoore** [comment]
Sorry I saw the mention too late! All looks fine to me. Thanks!

**Pull request merged**
