### PR TITLE
[azure-provider] Generate names for dataDisks

### PR DESCRIPTION
**Pull request by djmitche**
..to allow their deletion during deprovisioning

I'm going to test this out in my dev environment.

Bugzilla Bug: [1631824](https://bugzilla.mozilla.org/show_bug.cgi?id=1631824)

### CODE REVIEW

**Comment by djmitche** [comment]
The failures above are unrelated.. but I can't figure out how to set up the Azure provider for my dev env, so I've not finished that yet.

**Comment by djmitche** [comment]
Welp, I finally got the provider working, and it didn't delete any of the disks (including the OS disk)

**Comment by djmitche** [comment]
The `disks` array appears to be empty in providerData.

**Comment by djmitche** [comment]
Ah, I see why: once the instance exists, `checkWorker` assumes everything's OK and doesn't call `provisionResources` again, so the `modifyFn` is never called, which is what fills in the disk information.

There's a pretty bad race condition here, anyway, between finishing the provisioning process (gathering the information about the worker) and the worker registering and going to the RUNNING state.

**Comment by djmitche** [comment]
This has been awful, which is a bit better than I expected.  I'll work on addressing that race condition tomorrow.  Ideally:
 * can fix the race
 * can just name all disks in advance so that we don't need to capture them back after the VM is created

**Comment by djmitche** [comment]
Well, I tried both of those "ideally" items.  [narrator voice]Let's see what happens[/narrator voice]

**Comment by djmitche** [comment]
OMG it's green

**Comment by djmitche** [comment]
So, I think this is another bug, but if you delete an instance when it's still in the REQUESTED state, then `provisionResources` just keeps patiently waiting for it to show up.  I'll slap another coat of paint over that crack and hope it doesn't get any bigger.

**Comment by djmitche** [comment]
OK, this version works in dev, both for when a worker is removed with `removeWorker` and for when the vm is deleted via the portal.

**Review by imbstack — APPROVED** [review]
I think this makes sense. Thanks for dealing with this

**Pull request merged**
