### PR TITLE
Make netlify rootUrl point to firefox-ci deployment

### PR DESCRIPTION
**Pull request by helfi92**
Cleanup work.

### CODE REVIEW

**Comment by vishakhanihore** [comment]
@helfi92 What about having a `netlify deployment` badge in our readME too ?

**Comment by helfi92** [comment]
> @helfi92 What about having a netlify deployment badge in our readME too ?

Sure.

**Comment by vishakhanihore** [comment]
@helfi92 For making the badge for netlify for readME I will need the project-id.
It can be found in : 
- visit your project settings, 
- scroll to "Status badges" under "General", 
- copy the ID between "/api/v1/badges/" and "/deploy-status" in the code sample

After this, I will create a PR for the badge for netlify status which will be of the same type of we are using in `readME`

**Comment by helfi92** [comment]
[Netlify Status](https://app.netlify.com/sites/taskcluster-web/deploys)

**Pull request merged**
