### PR TITLE
Fix: 'Reference Links' box links are incorrect in README

### LINKED ISSUE #4722: "Reference Links" box links are incorrect in README
For example, look at the links in the box in the upper-right of https://docs.taskcluster.net/docs/reference/core/secrets

### PR DESCRIPTION
**Pull request by rbrishabh**
Fixes #4722 

hey @djmitche! what do you think about this fix? :) 
thanks!

### CODE REVIEW

**Comment by djmitche** [comment]
I'm testing it out now, but it will need a changelog.  Can you add one?

**Comment by rbrishabh** [comment]
yes, sure!

**Review by djmitche — CHANGES_REQUESTED** [review]
I mentioned these in Matrix but: this works great, just needs some lint and a changelog :)

**Comment by rbrishabh** [comment]
@djmitche ok I think this is ready now!

**Comment by djmitche** [comment]
Awesome - I'll check back when the tests are green :)

**Review by djmitche — APPROVED** [review]

**Pull request merged**
