### PR TITLE
Refactor monitoring to use a singleton manager

### PR DESCRIPTION
**Pull request by djmitche**
With this change, there is a single defaultMonitorManager, which can be
configured at module load time and can be set up *once*, resulting in a
root monitor.  After that, child monitors are generated from that root
monitor.  This resembles the successful azure-entities approach.

Concrete changes:
 * logging cannot be disabled
 * root logger is now named `taskcluster.<serviceName>` (no `.root`)
 * `pretty` setup option has been replaced with `debug`, which causes
   pretty log output to the debug log (and is enabled by default in
   tests)
 * `mock` setup option has been replaced with `fake` because it's a
   fake, not a mock.
 * `monitor.monitor(name)` invocation is now `monitor.childMonitor(name)`
 * taskcluster-lib-testing has a `withMonitor` function that supports
   setting up a monitor for testing services

I apologize for the huge diff.  This required changes to most tests, and also involved a bunch of moving existing code around (for example between the Monitor and MonitorManager classes).  I didn't see any way to make some changes without making all of the changes.

### CODE REVIEW

**Comment by djmitche** [comment]
Note that this has also removed the undocumented `monitor` parameter from tc-client constructors.  It seems that wasn't used in our services, and is very unlikely to be used elsewhere.

**Comment by owlishDeveloper** [comment]
wth is tc-cat doing here? also, queue tests are failing

**Comment by djmitche** [comment]
Yeah, I'm looking at queue.  And, tc-cat was enabled for my org -- i disabled it.

**Comment by djmitche** [comment]
Ah, queue fix was easy, fixed in a sec.

**Comment by owlishDeveloper** [comment]
> And, tc-cat was enabled for my org

mm, I'm not following - why would it be commenting in a PR in a taskcluster org? Or was enabled here?

**Comment by djmitche** [comment]
It commented on the push to the branch for this PR, which is in my org.

**Comment by owlishDeveloper** [comment]
> It commented on the push to the branch for this PR, which is in my org.

you essentially repeated the sentence I don't understand :) Can you re-phrase?

**Comment by djmitche** [comment]
I think we sorted the tc-cat question in Slack.

@owlishDeveloper did you want to review this too or is it OK to merge with @imbstack's r+?

**Comment by owlishDeveloper** [comment]
clear for merging!

**Comment by djmitche** [comment]
rebased with no substantive changes

**Comment by djmitche** [comment]
Deployed Everywhere.

**Pull request merged**
