### PR TITLE
Update base_ref evaluation

### PR DESCRIPTION
**Pull request by lotas**
Using https://github.com/mozilla-mobile/android-components/commit/6bd8e999946eca39d3925e41a8166da6ccdd6901 as a reference

### CODE REVIEW

**Review by matt-boris — APPROVED** [review]
LGTM as long as this works for `yarn staging-release` as well?

**Comment by lotas** [comment]
> LGTM as long as this works for `yarn staging-release` as well?

Yep, all green: https://github.com/taskcluster/staging-releases/runs/9292376300

**Comment by matt-boris** [comment]
> Yep, all green

:shipit:

**Review by petemoore — APPROVED** [review]
:rubberstamp: ;-)

**Pull request merged**
