### PR TITLE
Max length adjust

### LINKED ISSUE #1986: Hooks have limiting length
https://github.com/taskcluster/taskcluster/blob/d740e32431941ce438de2060f3336272cb462bed/services/hooks/src/api.js#L16

I have a case where I was creating a hook as it would be defined if it was a `cron_target` for the android-components repo, and it was defined as `project-releng/cron-task-mozilla-mobile-android-components/geckoview-update-nightly`  [src](https://hg.mozilla.org/ci/ci-configuration/rev/7f48a015136d9f6c30bbf5a87ab2e0e88a80363e#l1.58)

This one is length 68... is `{1,64}` an actual limit here, or can we go larger?

### PR DESCRIPTION
**Pull request by pret3nti0u5**
Github Bug/Issue: Fixes #1986

### CODE REVIEW

**Comment by djmitche** [comment]
Correct.

**Comment by djmitche** [comment]
Nice work @pret3nti0u5!  That one required fewer changes than I expected.  Sometimes bugs work out that way.  Sometimes they're a lot *more* work than expected :)

**Comment by pret3nti0u5** [comment]
@djmitche To be honest you pretty much laid out all I had to do. Thanks for guiding me! This is my first merged PR on a major open source project. Looking forward to contributing some more :)

**Comment by djmitche** [comment]
Awesome!  https://codetribute.mozilla.org/projects/taskcluster has a nice list of additional bugs and issues for TC.

**Pull request merged**
