### PR TITLE
[UI] Rename Purge Cache to Purge Caches

### PR DESCRIPTION
**Pull request by lailahgrant**
Bugzilla Bug: [XXXXX](https://bugzilla.mozilla.org/show_bug.cgi?id=XXXXX)

Github Bug/Issue: Fixes #XXXX

### CODE REVIEW

**Comment by lailahgrant** [comment]
> Good job!

Thanks, Sir @helfi92 ... I'm just surprised that this has been merged there and then.  Did I miss something, What happened Sir :flushed: ???

**Comment by helfi92** [comment]
I just added a changelog to make the tests pass. https://github.com/taskcluster/taskcluster/blob/master/dev-docs/best-practices/changelog.md

**Comment by lailahgrant** [comment]
Thank you very much @helfi92 , now I should work on my Git knowledge.
I will start  by going through progit pdf.
please feel free to tell me about more resources.
This has really been fun and challenging :relieved:

**Comment by helfi92** [comment]
Good idea!

**Pull request merged**
