### PR TITLE
Stop using two json-stable-stringify packages

### PR DESCRIPTION
**Pull request by imbstack**
Just noticed this while I was working on something else. I can't see any reason that both need to exist

### CODE REVIEW

**Comment by djmitche** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1630958#c4 highlights what *was* the reason.  But, tc-lib-entities is gone now, so it's probably OK (CI will tell!)

**Review by djmitche — APPROVED** [review]
👍🏽

**Comment by imbstack** [comment]
converting to draft until we get a way to get pretty-printing of some of this

**Comment by petemoore** [comment]
@imbstack shall we just close this?

**Pull request closed without merging**
