### PR TITLE
Placeholder for '/tasks' and '/tasks/groups'

### LINKED ISSUE #1416: [UI] Search placeholder
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/tasks
2. Look at the search component

Screen Shot 2019-09-30 at 4 45 55 PM

**Expected behavior**
A placeholder that tells the user what they should search for. For example, in https://taskcluster-ui.herokuapp.com/tasks, it should say "Search Task ID" instead of "Search". The change should be done to the following views:

https://taskcluster-ui.herokuapp.com/tasks -> Search Task ID
https://taskcluster-ui.herokuapp.com/tasks/SRPZN658R-y9nFjCq1TAKA -> Search Task ID
https://taskcluster-ui.herokuapp.com/tasks/groups -> Search Task Group ID
https://taskcluster-ui.herokuapp.com/tasks/groups/Sc6I-RrRR2ejlKVk0Z44TQ -> Search Task Group ID

### PR DESCRIPTION
**Pull request by Soundharyaam**
A unique placeholder has been added for  '/tasks' and '/tasks/groups' routes. 

Resolves #1416

### CODE REVIEW

**Comment by Soundharyaam** [comment]
Thank you @djmitche. Made a commit for linting.

**Comment by djmitche** [comment]
Looks good to me! @helfi92 will be back next week, and will offer his review at that time.

**Comment by Soundharyaam** [comment]
Okay @djmitche.

**Comment by Soundharyaam** [comment]
Thank you @helfi92

**Pull request merged**
