### PR TITLE
Handle unknown providerId without crashing

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by imbstack** [comment]
Do we want to make codecov not complain when a patch reduces coverage?

**Comment by djmitche** [comment]
It seems like I should probably do a better job of testing this.

But the loss of 1% overall seems related to things in tc-queue getting hit or not hit..

**Comment by imbstack** [comment]
It allows that 1% now, the project check is green. The 41% coverage for this patch is what failed. We can make it allow things like this and not fail.

**Comment by djmitche** [comment]
OK, added some coverage :crossed_fingers:

**Comment by djmitche** [comment]
> 84% of diff hit (target 73%)
:grin:

**Comment by djmitche** [comment]
Re-flagging for review mainly for the change to main.js.

**Pull request merged**
