### PR TITLE
[UI] Make a worker pool that is "scheduled for deletion" editable #1685

### PR DESCRIPTION
**Pull request by km-js**
Bugzilla Bug: [1581863](https://bugzilla.mozilla.org/show_bug.cgi?id=1581863)

#1685 

This bug can be resolved by making the worker pool that is "scheduled for deletion" behave like the other worker pools that are editable.

Changes Done:
Removed the conditional operator so that both types of worker pools can work alike.

### CODE REVIEW

**Comment by km-js** [comment]
Hey @helfi92, sorry for being late but can you help me a lil bit to understand what exactly we have to do with the provider field. Do we have to set it's initial value to null provider?

**Comment by helfi92** [comment]
Now that I think about it, I think it makes sense for it to not have a provider selected.

**Comment by helfi92** [comment]
Before we merge, we need to remove the `package-lock.json` file.

**Comment by helfi92** [comment]
@all-contributors please add @km-js for code.

**Pull request merged**
