### PR TITLE
Fix Github Quickstart

### PR DESCRIPTION
**Pull request by arku**
Bugzilla Bug: [1564510](https://bugzilla.mozilla.org/show_bug.cgi?id=1564510)

## Changes
- Introduces the concept of `eventGroups` (`pullRequest` is an event group which has 4 possible events - `closed`, `opened`, `reopened`, `synchronize`). Available `eventGroups` - `pullRequest`, `push`, and `release`
- Generates a `match` clause in `.taskcluster.yml` for each checked `eventGroup` (If a user checks 'push'  event, a new match clause with a task definition is generated)
- If `release` event is enabled, no command is generated. This is because we assume the user wants to do custom stuff and not run tests on a `release` event.

/cc @djmitche

### CODE REVIEW

**Comment by owlishDeveloper** [comment]
Hi @arku, thank you so much for working on this! I have to say I am impressed with your abilities. However, I think we misjudged Quickstart for v1 as a good first bug. I see that this component actually needs some substantial re-thinking and re-design, and continuing to develop the existing code makes little sense (especially considering this UI is not in production yet). This is not much fun, and I think it will be best if we complete this work ourselves. I am going to close this PR and the ticket. Thank you again for working on this, and I hope to see more PRs from you in this repo!

**Comment by arku** [comment]
@owlishDeveloper  No worries!

Looking forward to see what you guys come up with :slightly_smiling_face:

**Comment by djmitche** [comment]
Thanks for understanding @arku and sorry that I gave you a false start -- @owlishDeveloper is the expert here!

**Comment by arku** [comment]
@djmitche No problem at all. It was fun working on the Quickstart stuff :smile:

**Pull request closed without merging**
