### PR TITLE
Material-UI upgrade

### PR DESCRIPTION
**Pull request by aryamanpuri**

### CODE REVIEW

**Comment by vishakhanihore** [comment]
@Rolikasi Aren't all such changes covered in your PR ?

**Comment by aryamanpuri** [comment]
> @Rolikasi Aren't all such changes covered in your PR ?
No , this pr covers all the changes in ui sub-directory .

**Comment by vishakhanihore** [comment]
> @Rolikasi Aren't all such changes covered in your PR ?
> No , this pr covers all the changes in ui sub-directory .

I think migrating to MUI 4.0 covers all such occurences in the complete web-app

**Comment by Rolikasi** [comment]
Yes, #1976 already covers all these changes and it's about to merge

**Comment by aryamanpuri** [comment]
@Rolikasi Okay got it  , so what should I do to this pr ?

**Comment by vishakhanihore** [comment]
You should close it 😅

**Comment by Rolikasi** [comment]
You can close it )

**Pull request closed without merging**
