### PR TITLE
[UI] Condense "Provisioners" Page

### LINKED ISSUE #2096: [UI] The "provisioners" page is not very dense.
If I go to https://firefox-ci-tc.services.mozilla.com/provisioners/ I can only see ~6 of 38 "provisioners"[1]. I wanted to look at what all was being used and this made it hard to get an overview.

[1] These no longer represent provisioners, but the part of the worker-pool name before the `\`, but the point still stands.

### PR DESCRIPTION
**Pull request by MooseJ**
Github Bug/Issue: Fixes #2096

### CODE REVIEW

**Comment by MooseJ** [comment]
So this is what I have so far for condensing the provisioners page. This is still a work in progress by the way. Let me know what you think!

Moved away from cards to a table
image

Put the Actions and Description of a Provisioner into a drawer component
image

Instead of having an Explore Work Type section/column, I turned the provisioner id into a link that lets you know what happens when you click on it if you hover over it
Workers-hover

**Comment by MooseJ** [comment]
And this is what the actions currently look like
Screen Shot 2019-12-01 at 8 51 42 PM

**Comment by helfi92** [comment]
@MooseJ I'm planning to merge this either tonight or tomorrow. Let me know if you want me to create a good-second-issue for you :)

**Comment by MooseJ** [comment]
That's awesome to hear, thank you! 😄 I would definitely be down for more issues.

**Comment by helfi92** [comment]
> That's awesome to hear, thank you! 😄 I would definitely be down for more issues.

I'll get back to you in a bit after creating some new issues :)

**Comment by helfi92** [comment]
OK, I created a couple of issues. Here's two that are relatively high in priority:

1. https://github.com/taskcluster/taskcluster/issues/2130
2. https://github.com/taskcluster/taskcluster/issues/2125

Just comment directly on the one you want to work at and I'll have it assigned to you :) As always, happy to answer any questions.

**Comment by helfi92** [comment]
@all-contributors please add @MooseJ for code.

**Pull request merged**
