### PR TITLE
[UI] Migrate to material-ui v4

### PR DESCRIPTION
**Pull request by helfi92**
Reverts taskcluster/taskcluster#1974.

### CODE REVIEW

**Comment by helfi92** [comment]
@Rolikasi Feel free to add your additions here.

**Comment by Rolikasi** [comment]
`remote: Permission to taskcluster/taskcluster.git denied to Rolikasi.`
Can't push to upstream <this branch>

**Comment by Rolikasi** [comment]
I can only open a new PR for this PR. 
https://github.com/taskcluster/taskcluster/pull/1980

**Comment by helfi92** [comment]
I noticed the following regression:

STR:

1. Navigate to http://localhost:5080/secrets/create
2. Open the calendar widget by clicking the calendar icon beside Expires

Expected:

Screen Shot 2019-11-14 at 4 09 24 PM

Actual:

Screen Shot 2019-11-14 at 4 08 28 PM

**Comment by helfi92** [comment]
@Rolikasi Any idea why this is happening?

**Comment by Rolikasi** [comment]
> 
> 
> @Rolikasi Any idea why this is happening?

Hmmm, styles from overrides in theme.js(`MuiPickersModal: {dialogAction: ...`) no longer append in calendar, I don't understand why. Also material-ui-pickers v2.2.4 uses material-ui v3 and there are new warnings. We need to update it too

**Comment by Rolikasi** [comment]
> 
> 
> Another regression:
> 
> Navigate to [http://localhost:5080/auth/clients/mozilla-auth0%2Fad|Mozilla-LDAP|adw%2Ftreeherder-production-FL-jZm](http://localhost:5080/auth/clients/mozilla-auth0%2Fad%7CMozilla-LDAP%7Cadw%2Ftreeherder-production-FL-jZm). The font-size in the markdown text area (the text area under "Expires") is smaller than than what is in [https://firefox-ci-tc.services.mozilla.com/auth/clients/mozilla-auth0%2Fad|Mozilla-LDAP|adw%2Ftreeherder-production-FL-jZm](https://firefox-ci-tc.services.mozilla.com/auth/clients/mozilla-auth0%2Fad%7CMozilla-LDAP%7Cadw%2Ftreeherder-production-FL-jZm)

There are 2 solutions: 
1) Add styles to @mozilla-frontend-infra/components/MarkdownTextArea because `TextFiled` in Write tab uses `fontSize: '1rem'`, but `Markdown` in Preview takes `fontSize` from parent element
In taskcluster `<CSSBaseline >` give body font-size: '0.875rem' after migration, so markdown is smaller now. I tried to add '1rem' to body in past and forgot about this regression.
2) Manually add styles to every MarkdownTextArea in taskcluster

**Comment by Rolikasi** [comment]
> 
> 
> > @Rolikasi Any idea why this is happening?
> 
> Hmmm, styles from overrides in theme.js(`MuiPickersModal: {dialogAction: ...`) no longer append in calendar, I don't understand why. Also material-ui-pickers v2.2.4 uses material-ui v3 and there are new warnings. We need to update it too

`MuiPickersModal: dialogAction` just doesn't work after migration to material-ui v4. We can override `MuiButton: { label: {... }}` directly in theme.js, hope it won't affect on other elements. What do you think @helfi92 ?

**Comment by helfi92** [comment]
I think that package was renamed to `@material-ui/pickers` when they migrated to v4. We could use that package instead. https://material-ui-pickers.dev/

**Comment by Rolikasi** [comment]
> 
> 
> I think that package was renamed to `@material-ui/pickers` when they migrated to v4. We could use that package instead. https://material-ui-pickers.dev/

I've already tried to use `"@material-ui/pickers": "^3.2.7"` package. not working(

**Comment by helfi92** [comment]
> I've already tried to use "@material-ui/pickers": "^3.2.7" package. not working(

Do you know why it wasn't working? What was wrong?

**Comment by Rolikasi** [comment]
> 
> 
> > I've already tried to use "@material-ui/pickers": "^3.2.7" package. not working(
> 
> Do you know why it wasn't working? What was wrong?

No, I don't. There are [1](https://github.com/mui-org/material-ui-pickers/issues/1356) [2](https://github.com/mui-org/material-ui-pickers/issues/1376) issues in that repo with same problem

**Comment by helfi92** [comment]
I think it's still possible to find a way to hack it. One moment.

**Comment by helfi92** [comment]
Here's a start:

```diff
diff --git a/ui/package.json b/ui/package.json
index 5b7a9b8d7..f04c4ae0f 100644
--- a/ui/package.json
+++ b/ui/package.json
@@ -20,6 +20,7 @@
     "@material-ui/core": "^4.5.1",
     "@material-ui/icons": "^4.5.1",
     "@material-ui/lab": "4.0.0-alpha.20",
+    "@material-ui/pickers": "^3.2.7",
     "@mdx-js/react": "^1.0.20",
     "@mdx-js/runtime": "^1.0.20",
     "@mozilla-frontend-infra/components": "^3.0.0",
@@ -59,7 +60,6 @@
     "markdown-it": "^10.0.0",
     "markdown-it-highlightjs": "^3.0.0",
     "markdown-it-link-attributes": "^3.0.0",
-    "material-ui-pickers": "2.2.4",
     "material-ui-treeview": "^4.0.0",
     "mdi-react": "^6.2.0",
     "mdx-loader": "^3.0.2",
diff --git a/ui/src/components/DatePicker/index.jsx b/ui/src/components/DatePicker/index.jsx
index 0e679934a..24f9d8bf7 100644
--- a/ui/src/components/DatePicker/index.jsx
+++ b/ui/src/components/DatePicker/index.jsx
@@ -2,9 +2,9 @@ import React, { Component } from 'react';
 import { func } from 'prop-types';
 import classNames from 'classnames';
 import {
-  DatePicker as MuiDatePicker,
+  KeyboardDatePicker,
   MuiPickersUtilsProvider,
-} from 'material-ui-pickers';
+} from '@material-ui/pickers';
 import { withStyles } from '@material-ui/core/styles';
 import DateFnsUtils from '@date-io/date-fns';
 import ChevronRightIcon from 'mdi-react/ChevronRightIcon';
@@ -39,10 +39,9 @@ export default class DatePicker extends Component {
 
     return (
       <MuiPickersUtilsProvider utils={DateFnsUtils}>
-        <MuiDatePicker
+        <KeyboardDatePicker
           className={classNames(classes.datePicker, className)}
           showTodayButton
-          keyboard
           keyboardIcon={<CalendarIcon />}
           rightArrowIcon={<ChevronRightIcon />}
           leftArrowIcon={<ChevronLeftIcon />}
diff --git a/ui/src/theme.js b/ui/src/theme.js
index 98c5e59dd..404d63287 100644
--- a/ui/src/theme.js
+++ b/ui/src/theme.js
@@ -303,6 +303,14 @@ const createTheme = isDarkTheme => {
           backgroundColor: THEME.SECONDARY,
         },
       },
+      MuiPickersToolbarText: {
+        toolbarTxt: {
+          color: THEME.PRIMARY_TEXT_DARK,
+        },
+        toolbarBtnSelected: {
+          color: THEME.PRIMARY_TEXT_DARK,
+        },
+      },
       MuiPickersToolbarButton: {
         toolbarBtn: {
           '&:hover, &:focus': {
@@ -352,10 +360,13 @@ const createTheme = isDarkTheme => {
         },
       },
       MuiPickersDay: {
-        isSelected: {
+        daySelected: {
           backgroundColor: THEME.SECONDARY,
+          color: isDarkTheme
+            ? THEME.PRIMARY_TEXT_LIGHT
+            : THEME.PRIMARY_TEXT_DARK,
         },
-        current: {
+        day: {
           color: isDarkTheme ? 'white' : '#000',
         },
       },
@@ -369,6 +380,18 @@ const createTheme = isDarkTheme => {
           },
         },
       },
+      MuiDialogActions: {
+        root: {
+          '& button': {
+            color: isDarkTheme ? 'white' : '#000',
+            '&:hover': {
+              backgroundColor: isDarkTheme
+                ? THEME.TEN_PERCENT_WHITE
+                : THEME.TEN_PERCENT_BLACK,
+            },
+          },
+        },
+      },
       MuiDrawer: {
         paper: {
           maxWidth: 500,
```

**Comment by helfi92** [comment]
A couple of points:
* Be sure to test on both light and dark theme
* I used the developer tools to look at the class names to have an idea of how to override the styles
* If you click on the year inside the dialog, a new view will show up allowing you to change the year. We should make sure the experience in that view is similar to current production site.

**Comment by Rolikasi** [comment]
I added minor changes. We don't need to change `current` to `day`. But add styles for `day` is good for UX. 
I fixed styles for year view.
Material-ui/pickers now shows the current year in center, not at top

**Comment by Rolikasi** [comment]
And thanks for help!)) I was stuck

**Comment by helfi92** [comment]
🎉

**Comment by Rolikasi** [comment]
> 
> 
> OK, I think we can give this another try :)

🎉🎉🎉🎉🎉

**Pull request merged**
